//! Auto attacks. Port of `Class/Common/Spells/MainhandAttack.*`, `OffhandAttack.*` and the
//! Warrior variants `Class/Warrior/Spells/MainhandAttackWarrior.*` / `OffhandAttackWarrior.*`.
//!
//! One [`AutoAttack`] per hand keeps the swing timer (`next_expected_use`, re-timed on haste
//! changes and parry haste), the iteration counter that invalidates stale swing events, and the
//! offhand damage penalty. A swing rolls on the white attack table and reports its outcome and
//! the rage it generated in a [`SwingReport`]; the caller (the character's spell context) feeds
//! the statistics and runs the proc sources. Rage generation is generic: hosts that use rage
//! gain it in [`AutoAttackHost::gain_swing_rage`], others return `None`.
//!
//! Forever normalizes white swing rage: a landed swing gives a fixed amount per second of base
//! weapon speed, independent of the damage (see [`swing_rage`]).

use crate::combat_roll::PhysicalAttackResult;
use crate::engine::EventKind;
use crate::proc::ProcSource;
use crate::spell::{AttackOutcome, Hand, SpellHost};

/// Tolerance for "the swing was due before now". Port of the `-0.0001` check in
/// `update_next_expected_use`.
const SWING_EPSILON: f64 = 0.0001;

/// What an auto attack needs from the world beyond what a spell needs.
pub trait AutoAttackHost: SpellHost {
    /// Current (hasted) speed of the weapon in `hand`; `None` when the hand is empty.
    fn weapon_speed(&self, hand: Hand) -> Option<f64>;
    fn weapon_skill(&self, hand: Hand) -> u32;
    /// Rolls a white swing of `hand` on the auto attack table.
    fn roll_melee_hit(&mut self, hand: Hand) -> PhysicalAttackResult;
    /// The damage multiplier of a glancing blow with `weapon_skill`.
    fn glancing_blow_dmg_penalty(&mut self, weapon_skill: u32) -> f64;
    fn random_non_normalized_oh_dmg(&mut self) -> f64;
    /// Damage multiplier of a white crit.
    fn melee_crit_dmg_mod(&self) -> f64;
    /// Gains the rage of a landed swing of `hand` (see [`swing_rage`]); returns the rage
    /// actually gained after the cap, or `None` for characters that do not use rage.
    fn gain_swing_rage(&mut self, hand: Hand) -> Option<f64>;
    /// Schedules the player's reaction to the swing. Port of `Character::add_player_reaction_event`.
    fn add_player_reaction_event(&mut self);
    fn is_melee_attacking(&self) -> bool;
}

/// What one swing did.
#[derive(Debug, Clone, PartialEq)]
pub struct SwingReport {
    pub hand: Hand,
    pub attack: AttackOutcome,
    /// Rage generated by the swing (after the cap, fractional), if any.
    pub rage_gained: Option<f64>,
    pub proc_sources: Vec<ProcSource>,
}

/// The white swing of one hand. Port of `MainhandAttack` / `OffhandAttack`.
#[derive(Debug, Clone, PartialEq)]
pub struct AutoAttack {
    hand: Hand,
    next_expected_use: f64,
    last_used: f64,
    iteration: u32,
    /// Multiplier on offhand damage (`0.5`, raised by Dual Wield Specialization).
    offhand_penalty: f64,
}

impl AutoAttack {
    pub const DEFAULT_OFFHAND_PENALTY: f64 = 0.5;

    pub fn new(hand: Hand) -> Self {
        AutoAttack {
            hand,
            next_expected_use: 0.0,
            last_used: 0.0,
            iteration: 0,
            offhand_penalty: Self::DEFAULT_OFFHAND_PENALTY,
        }
    }

    pub fn hand(&self) -> Hand {
        self.hand
    }

    pub fn name(&self) -> &'static str {
        match self.hand {
            Hand::Mainhand => "Mainhand Attack",
            Hand::Offhand => "Offhand Attack",
        }
    }

    pub fn offhand_penalty(&self) -> f64 {
        self.offhand_penalty
    }

    /// Sets the offhand damage multiplier (talents). Ignored for the mainhand.
    pub fn set_offhand_penalty(&mut self, penalty: f64) {
        self.offhand_penalty = penalty;
    }

    /// The source a landed swing of this hand produces for the proc checks (and the charge
    /// consumption).
    pub fn proc_source(&self) -> ProcSource {
        match self.hand {
            Hand::Mainhand => ProcSource::MainhandSwing,
            Hand::Offhand => ProcSource::OffhandSwing,
        }
    }

    // --- Swing timer ---

    /// Time of the last completed swing.
    pub fn last_used(&self) -> f64 {
        self.last_used
    }

    /// When the next swing lands, never in the past. Port of `get_next_expected_use`.
    pub fn next_expected_use(&self, now: f64) -> f64 {
        self.next_expected_use.max(now)
    }

    /// Seconds until the next swing.
    pub fn time_until_next_swing(&self, now: f64) -> f64 {
        self.next_expected_use(now) - now
    }

    /// Re-times the pending swing after the attack speed changed by `haste_change` (a fraction:
    /// `1.0` doubles the speed, `-0.5` halves it). Port of `update_next_expected_use`.
    pub fn update_next_expected_use(&mut self, now: f64, haste_change: f64) {
        let mut remaining = self.next_expected_use - now;
        if remaining < -SWING_EPSILON {
            return;
        }
        if haste_change < 0.0 {
            remaining *= 1.0 - haste_change;
        } else {
            remaining /= 1.0 + haste_change;
        }
        self.next_expected_use = now + remaining;
    }

    /// Parry haste: the boss parrying advances the swing. Port of
    /// `update_next_expected_use_for_parry` (see the classic-warrior wiki on parry haste).
    pub fn update_next_expected_use_for_parry(&mut self, now: f64, speed: f64) {
        let remaining = self.next_expected_use - now;
        let fraction = remaining / speed;
        if fraction > 0.5 {
            self.next_expected_use = self.last_used + speed - 0.4 * speed;
        } else if fraction >= 0.2 {
            self.next_expected_use -= 0.2 * speed;
        }
    }

    /// Records a swing at `now` and times the next one. Port of `complete_swing`.
    pub fn complete_swing(&mut self, now: f64, speed: f64) {
        self.last_used = now;
        self.next_expected_use = now + speed;
    }

    /// Restarts the swing timer from `now` (Slam). Port of `reset_swingtimer` without the
    /// rescheduling, which [`AutoAttack::reset_swing_timer_and_schedule`] adds.
    pub fn reset_swing_timer(&mut self, now: f64, speed: f64) {
        self.next_expected_use = now + speed;
    }

    /// Port of `reset_swingtimer`: restarts the timer and, while attacking, schedules the swing.
    pub fn reset_swing_timer_and_schedule(&mut self, host: &mut impl AutoAttackHost) {
        let now = host.engine().current_time();
        let speed = host.weapon_speed(self.hand).unwrap_or(0.0);
        self.reset_swing_timer(now, speed);
        if host.is_melee_attacking() {
            self.schedule_next(host);
        }
    }

    /// Whether a swing event with `iteration` is the latest scheduled one.
    pub fn attack_is_valid(&self, iteration: u32) -> bool {
        self.iteration == iteration
    }

    pub fn iteration(&self) -> u32 {
        self.iteration
    }

    /// Schedules the next swing event for this hand. Port of `add_next_mh_attack` /
    /// `add_next_oh_attack`.
    pub fn schedule_next(&mut self, host: &mut impl AutoAttackHost) {
        self.iteration += 1;
        let (character, iteration) = (host.character_id(), self.iteration);
        let time = self.next_expected_use(host.engine().current_time());
        let kind = match self.hand {
            Hand::Mainhand => EventKind::MainhandMeleeHit {
                character,
                iteration,
            },
            Hand::Offhand => EventKind::OffhandMeleeHit {
                character,
                iteration,
            },
        };
        host.engine_mut()
            .add_event(crate::engine::Event::new(time, kind));
    }

    // --- Swinging ---

    /// Swings: completes the swing timer and rolls the damage. Port of `spell_effect`.
    pub fn perform(&mut self, host: &mut impl AutoAttackHost) -> SwingReport {
        let now = host.engine().current_time();
        let speed = host.weapon_speed(self.hand).unwrap_or(0.0);
        self.complete_swing(now, speed);
        self.calculate_damage(host)
    }

    /// An extra swing (Sword Specialization, Windfury): swings now and re-times the next one.
    /// Port of `extra_attack`.
    pub fn extra_attack(&mut self, host: &mut impl AutoAttackHost) -> SwingReport {
        let report = self.perform(host);
        self.schedule_next(host);
        report
    }

    /// Port of `MainhandAttackWarrior::calculate_damage` / `OffhandAttackWarrior::calculate_damage`
    /// (the generic versions minus the rage generation).
    fn calculate_damage(&mut self, host: &mut impl AutoAttackHost) -> SwingReport {
        if self.hand == Hand::Mainhand {
            host.add_player_reaction_event();
        }
        let hand = self.hand;
        let weapon_skill = host.weapon_skill(hand);
        let result = host.roll_melee_hit(hand);
        let mut report = SwingReport {
            hand,
            attack: AttackOutcome {
                result,
                damage: 0,
                threat: 0.0,
                execution_time: 0.0,
            },
            rage_gained: None,
            proc_sources: Vec::new(),
        };

        match result {
            PhysicalAttackResult::Miss => {
                report.proc_sources.push(ProcSource::MeleeMiss);
                return report;
            }
            // Avoided swings give no rage in Forever.
            PhysicalAttackResult::Dodge => {
                report.proc_sources.push(ProcSource::MeleeDodge);
                return report;
            }
            PhysicalAttackResult::Parry => {
                report.proc_sources.push(ProcSource::MeleeParry);
                return report;
            }
            _ => {}
        }

        let raw = match hand {
            Hand::Mainhand => host.random_non_normalized_mh_dmg(),
            Hand::Offhand => host.random_non_normalized_oh_dmg() * self.offhand_penalty,
        };
        let mut damage = damage_after_modifiers(host, raw);
        match result {
            PhysicalAttackResult::Critical | PhysicalAttackResult::BlockCritical => {
                damage = (damage * host.melee_crit_dmg_mod()).round();
            }
            PhysicalAttackResult::Glancing => {
                damage = (damage * host.glancing_blow_dmg_penalty(weapon_skill)).round();
            }
            _ => {
                damage = damage.round();
            }
        }
        // A blocked swing lands for its damage less the target's block value; one the block
        // value absorbs entirely is a full block and counts as avoided for the procs. There is
        // no Forever data on block rage; both give the swing's rage like a landed hit.
        if matches!(
            result,
            PhysicalAttackResult::Block | PhysicalAttackResult::BlockCritical
        ) {
            damage -= f64::from(host.target_block_value());
            if damage <= 0.0 {
                report.proc_sources.push(ProcSource::MeleeFullBlock);
                report.rage_gained = host.gain_swing_rage(hand);
                return report;
            }
        }
        // A landed swing is reported by its hand (`melee_mh_white_hit_effect` /
        // `melee_oh_white_hit_effect`); a crit additionally by its result, for the crit-only
        // procs (Flurry, Deep Wounds). See `ProcSource::from_masks`.
        report.proc_sources.push(self.proc_source());
        if matches!(
            result,
            PhysicalAttackResult::Critical | PhysicalAttackResult::BlockCritical
        ) {
            report.proc_sources.push(ProcSource::MeleeCritical);
        }
        report.attack.damage = damage.max(0.0) as u32;
        report.attack.threat = f64::from(report.attack.damage) * host.total_threat_mod();
        report.rage_gained = host.gain_swing_rage(hand);
        report
    }

    // --- Lifecycle ---

    /// Start of an iteration. Port of `reset_effect`.
    pub fn reset(&mut self) {
        self.next_expected_use = 0.0;
        self.last_used = 0.0;
    }

    /// Port of `prepare_set_of_combat_iterations_spell_specific`.
    pub fn prepare_set_of_combat_iterations(&mut self) {
        self.reset();
        self.iteration = 0;
    }
}

/// Port of `Spell::damage_after_modifiers` for swings.
fn damage_after_modifiers(host: &impl AutoAttackHost, damage: f64) -> f64 {
    let armor_reduction = 1.0
        - crate::mechanics::Mechanics::reduction_from_armor(
            host.target_armor(),
            host.caster_level(),
        );
    (damage * host.total_physical_damage_mod() + f64::from(host.flat_physical_damage_bonus()))
        * armor_reduction
}

/// Rage per second of base weapon speed of a one-hander (fists included). Forever beta 1.60.1
/// combat logs, <https://github.com/magey/forever-warrior/issues/3>: 1.5, 1.6, 2.0 and 2.1 speed
/// one-handers all landed within 1 % of 3.46.
pub const ONE_HAND_RAGE_PER_SECOND: f64 = 3.46;
/// Rage per second of base weapon speed of a two-hander (3.0 and 3.2 swords, exact to the
/// tenth): 1.3 times the one-hand rate.
pub const TWO_HAND_RAGE_PER_SECOND: f64 = 4.5;
/// The off-hand generates half the one-hand rate (issue comment, 1.8 / 1.6 daggers);
/// Dual Wield Specialization's `OFFHAND_RAGE_PERCENT` scales it back up.
pub const OFFHAND_RAGE_FACTOR: f64 = 0.5;

/// Rage of one landed white swing, before the off-hand rage percentage: a fixed amount per
/// second of **base** weapon speed, with no damage, crit or glancing term. The logs were
/// unhasted, so whether haste shortens the speed used here is untested; the base speed is the
/// assumption (as in TBC), so haste still adds rage by adding swings. Measured at levels 8-22;
/// taken as level independent.
pub fn swing_rage(base_speed: f64, two_hand: bool, hand: Hand) -> f64 {
    let per_second = if two_hand {
        TWO_HAND_RAGE_PER_SECOND
    } else {
        ONE_HAND_RAGE_PER_SECOND
    };
    let hand_factor = match hand {
        Hand::Mainhand => 1.0,
        Hand::Offhand => OFFHAND_RAGE_FACTOR,
    };
    per_second * base_speed * hand_factor
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::buff::{Buff, BuffApplication};
    use crate::combat_roll::IncludedOutcomes;
    use crate::cooldown::CooldownControl;
    use crate::effect::EffectHost;
    use crate::engine::Engine;
    use crate::ids::{BuffId, CharId, CooldownId, SpellId};
    use crate::resource::{Rage, ResourceType};
    use crate::spell::dbc::AuraState;
    use crate::spell::modifiers::SpellModifiers;
    use crate::spell::record::EquippedItems;
    use crate::spell::CastReport;
    use crate::stance::Stance;
    use crate::stats::CharacterStats;
    use crate::target::Target;
    use std::collections::VecDeque;

    struct World {
        engine: Engine,
        stats: CharacterStats,
        target: Target,
        rage: Rage,
        /// Base main-hand speed; the swing timer uses it divided by `haste`.
        mh_speed: f64,
        haste: f64,
        two_hand: bool,
        offhand_rage_percent: i32,
        oh_speed: Option<f64>,
        rolls: VecDeque<PhysicalAttackResult>,
        rolled_hands: Vec<Hand>,
        glancing_penalty: f64,
        attacking: bool,
        reactions: u32,
        armor: i32,
        block_value: u32,
        rage_user: bool,
        modifiers: SpellModifiers,
    }

    impl World {
        fn new() -> Self {
            let mut engine = Engine::new();
            engine.prepare_iteration(0.0);
            World {
                engine,
                stats: CharacterStats::new(),
                target: Target::new(63),
                rage: Rage::new(),
                mh_speed: 2.6,
                haste: 1.0,
                two_hand: false,
                offhand_rage_percent: 0,
                oh_speed: Some(1.8),
                rolls: VecDeque::new(),
                rolled_hands: Vec::new(),
                glancing_penalty: 0.7,
                attacking: true,
                reactions: 0,
                armor: 0,
                block_value: 0,
                rage_user: true,
                modifiers: SpellModifiers::new(),
            }
        }

        fn advance_to(&mut self, time: f64) {
            self.engine
                .add_event(crate::engine::Event::new(time, EventKind::EncounterEnd));
            while let Some(event) = self.engine.next_event() {
                if let EventKind::EncounterEnd = event.kind {
                    break;
                }
            }
        }

        fn swing_events(&self) -> Vec<(f64, EventKind)> {
            let mut queue = self.engine.queue().clone();
            let mut events = Vec::new();
            while let Some(event) = queue.pop() {
                if matches!(
                    event.kind,
                    EventKind::MainhandMeleeHit { .. } | EventKind::OffhandMeleeHit { .. }
                ) {
                    events.push((event.time, event.kind));
                }
            }
            events
        }
    }

    impl EffectHost for World {
        fn caster_level(&self) -> u32 {
            60
        }
        fn combo_points(&self) -> u32 {
            0
        }
        fn gain_combo_points(&mut self, _: u32) {}
        fn spend_combo_points(&mut self) {}
        fn resource_level(&self, _: ResourceType) -> u32 {
            self.rage.current()
        }
        fn gain_resource(&mut self, _: ResourceType, amount: u32) -> u32 {
            self.rage.gain(amount)
        }
        fn melee_ap(&self) -> u32 {
            1000
        }
        fn random_in_range(&mut self, min: f64, max: f64) -> f64 {
            (min + max) / 2.0
        }
        fn random_normalized_mh_dmg(&mut self) -> f64 {
            0.0
        }
        fn random_non_normalized_mh_dmg(&mut self) -> f64 {
            // 100 + 2.6 * 1000 / 14
            100.0 + self.mh_speed * 1000.0 / 14.0
        }
        fn roll_melee_ability(
            &mut self,
            _: IncludedOutcomes,
            _: u32,
            _: bool,
        ) -> PhysicalAttackResult {
            unreachable!()
        }
        fn stats_mut(&mut self) -> &mut CharacterStats {
            &mut self.stats
        }
        fn target_mut(&mut self) -> &mut Target {
            &mut self.target
        }
        fn increase_melee_attack_speed(&mut self, _: u32) {}
        fn decrease_melee_attack_speed(&mut self, _: u32) {}
        fn swap_stance(&mut self, _: Stance) {}
        fn spell_modifiers(&self) -> &SpellModifiers {
            &self.modifiers
        }
        fn spell_modifiers_mut(&mut self) -> &mut SpellModifiers {
            &mut self.modifiers
        }
        fn add_extra_attacks(&mut self, _: u32) {}
        fn adjust_stance_rage_retained(&mut self, _: i32) {}
        fn adjust_offhand_damage_percent(&mut self, _: i32) {}
        fn adjust_offhand_rage_percent(&mut self, _: i32) {}
        fn adjust_offhand_copy(&mut self, _: u32, _: bool) {}
        fn override_actionbar_spell(&mut self, _: u32, _: u32, _: bool) {}
    }

    impl SpellHost for World {
        fn character_id(&self) -> CharId {
            CharId(1)
        }
        fn resource_type(&self) -> ResourceType {
            ResourceType::Rage
        }
        fn engine(&self) -> &Engine {
            &self.engine
        }
        fn engine_mut(&mut self) -> &mut Engine {
            &mut self.engine
        }
        fn combat_length(&self) -> f64 {
            300.0
        }
        fn on_global_cooldown(&self) -> bool {
            false
        }
        fn global_cooldown(&self) -> f64 {
            1.5
        }
        fn start_global_cooldown(&mut self) {}
        fn on_stance_cooldown(&self) -> bool {
            false
        }
        fn start_stance_cooldown(&mut self) {}
        fn cast_in_progress(&self) -> bool {
            false
        }
        fn start_cast(&mut self) -> u32 {
            1
        }
        fn complete_cast(&mut self, _: u32) {}
        fn casting_speed_mod(&self) -> f64 {
            1.0
        }
        fn casting_speed_flat_reduction(&self) -> u32 {
            0
        }
        fn stop_attack(&mut self) {
            self.attacking = false;
        }
        fn start_attack(&mut self) {
            self.attacking = true;
        }
        fn reset_swing_timers(&mut self) {}
        fn queue_next_swing(&mut self, _: SpellId) {}
        fn cancel_next_swing(&mut self) {}
        fn queued_next_swing(&self) -> Option<SpellId> {
            None
        }
        fn stance(&self) -> Stance {
            Stance::Battle
        }
        fn equipped_item_matches(&self, _: &EquippedItems) -> bool {
            true
        }
        fn caster_aura_state(&self, _: AuraState) -> bool {
            false
        }
        fn target_aura_state(&self, _: AuraState) -> bool {
            false
        }
        fn aura_active(&self, _: u32) -> bool {
            false
        }
        fn lose_resource(&mut self, _: ResourceType, amount: u32) {
            self.rage.lose(amount);
        }
        fn refund_resource(&mut self, _: ResourceType, amount: f64) {
            self.rage.gain_tenths(amount * 10.0);
        }
        fn cooldown(&self, _: CooldownId) -> &CooldownControl {
            unreachable!()
        }
        fn cooldown_mut(&mut self, _: CooldownId) -> &mut CooldownControl {
            unreachable!()
        }
        fn buff(&self, _: BuffId) -> &Buff {
            unreachable!()
        }
        fn buff_mut(&mut self, _: BuffId) -> &mut Buff {
            unreachable!()
        }
        fn apply_buff(&mut self, _: BuffId) -> BuffApplication {
            BuffApplication::NotApplied
        }
        fn cancel_buff(&mut self, _: BuffId) -> bool {
            false
        }
        fn enable_buff(&mut self, _: BuffId) {}
        fn disable_buff(&mut self, _: BuffId) {}
        fn trigger_spell(&mut self, _: u32, _: Option<f64>) -> Option<CastReport> {
            None
        }
        fn set_spell_effect_value(&mut self, _: u32, _: u32, _: f64) {}
        fn target_armor(&self) -> i32 {
            self.armor
        }
        fn target_block_value(&self) -> u32 {
            self.block_value
        }
        fn total_physical_damage_mod(&self) -> f64 {
            1.0
        }
        fn flat_physical_damage_bonus(&self) -> u32 {
            0
        }
        fn melee_ability_crit_dmg_mod(&self) -> f64 {
            2.2
        }
        fn total_threat_mod(&self) -> f64 {
            1.0
        }
        fn avg_mh_damage(&self) -> f64 {
            self.random_non_normalized_mh_dmg_const()
        }
        fn offhand_copy_active(&self, _: u32) -> bool {
            false
        }
        fn roll_offhand_melee_ability(
            &mut self,
            _: IncludedOutcomes,
            _: u32,
            _: bool,
        ) -> PhysicalAttackResult {
            unreachable!()
        }
        fn random_oh_weapon_dmg(&mut self, _: bool) -> f64 {
            unreachable!()
        }
        fn offhand_penalty(&self) -> f64 {
            unreachable!()
        }
    }

    impl World {
        fn random_non_normalized_mh_dmg_const(&self) -> f64 {
            100.0 + self.mh_speed * 1000.0 / 14.0
        }
    }

    impl AutoAttackHost for World {
        fn weapon_speed(&self, hand: Hand) -> Option<f64> {
            match hand {
                Hand::Mainhand => Some(self.mh_speed / self.haste),
                Hand::Offhand => self.oh_speed,
            }
        }
        fn weapon_skill(&self, _: Hand) -> u32 {
            300
        }
        fn roll_melee_hit(&mut self, hand: Hand) -> PhysicalAttackResult {
            self.rolled_hands.push(hand);
            self.rolls.pop_front().expect("no roll queued")
        }
        fn glancing_blow_dmg_penalty(&mut self, _: u32) -> f64 {
            self.glancing_penalty
        }
        fn random_non_normalized_oh_dmg(&mut self) -> f64 {
            50.0 + self.oh_speed.unwrap_or(0.0) * 1000.0 / 14.0
        }
        fn melee_crit_dmg_mod(&self) -> f64 {
            2.0
        }
        fn gain_swing_rage(&mut self, hand: Hand) -> Option<f64> {
            if !self.rage_user {
                return None;
            }
            let base_speed = match hand {
                Hand::Mainhand => self.mh_speed,
                Hand::Offhand => self.oh_speed?,
            };
            let mut rage = swing_rage(base_speed, self.two_hand, hand);
            if hand == Hand::Offhand {
                rage *= 1.0 + f64::from(self.offhand_rage_percent) / 100.0;
            }
            Some(f64::from(self.rage.gain_tenths(rage * 10.0)) / 10.0)
        }
        fn add_player_reaction_event(&mut self) {
            self.reactions += 1;
        }
        fn is_melee_attacking(&self) -> bool {
            self.attacking
        }
    }

    /// Rage per swing in tenths, as logged in magey/forever-warrior#3.
    #[test]
    fn swing_rage_matches_the_forever_logs() {
        let tenths = |speed, two_hand, hand| swing_rage(speed, two_hand, hand) * 10.0;
        for (speed, two_hand, logged) in [
            (1.5, false, 51.9),
            (1.6, false, 55.36),
            (2.0, false, 69.2),
            (2.1, false, 72.66),
            (3.0, true, 135.0),
            (3.2, true, 144.0),
        ] {
            let rage = tenths(speed, two_hand, Hand::Mainhand);
            assert!((rage - logged).abs() < 1e-9, "{speed}: {rage}");
        }
        // The off-hand generates half the one-hand rate.
        assert!((tenths(1.6, false, Hand::Offhand) - 27.68).abs() < 1e-9);
    }

    #[test]
    fn hit_crit_and_glancing_damage() {
        let mut world = World::new();
        let mut mh = AutoAttack::new(Hand::Mainhand);
        assert_eq!(mh.name(), "Mainhand Attack");
        assert_eq!(mh.proc_source(), ProcSource::MainhandSwing);

        // [286] = 100 + (2.6 * 1000 / 14)
        world.rolls.push_back(PhysicalAttackResult::Hit);
        let report = mh.perform(&mut world);
        assert_eq!(report.attack.result, PhysicalAttackResult::Hit);
        assert_eq!(report.attack.damage, 286);
        assert_eq!(report.attack.threat, 286.0);
        assert_eq!(report.attack.execution_time, 0.0);
        // 3.46 × 2.6 = 8.996 rage: 89 tenths, the 0.96 carried.
        assert_eq!(report.rage_gained, Some(8.9));
        assert_eq!(world.rage.current_tenths(), 89);
        assert_eq!(report.proc_sources, vec![ProcSource::MainhandSwing]);
        assert_eq!(world.reactions, 1);
        assert_eq!(mh.last_used(), 0.0);
        assert_eq!(mh.next_expected_use(0.0), 2.6);

        // [571] = 286 * 2.0
        world.rolls.push_back(PhysicalAttackResult::Critical);
        let report = mh.perform(&mut world);
        assert_eq!(report.attack.damage, 571);
        assert_eq!(
            report.proc_sources,
            vec![ProcSource::MainhandSwing, ProcSource::MeleeCritical],
            "a crit is a landed swing and a crit"
        );
        // No crit bonus: 0.96 + 89.96 = 90.92 tenths.
        assert_eq!(report.rage_gained, Some(9.0));

        world.rolls.push_back(PhysicalAttackResult::Glancing);
        let report = mh.perform(&mut world);
        assert_eq!(report.attack.damage, (285.714 * 0.7f64).round() as u32);
        assert_eq!(report.proc_sources, vec![ProcSource::MainhandSwing]);
        // Glancing blows give full rage: 0.92 + 89.96 = 90.88 tenths.
        assert_eq!(report.rage_gained, Some(9.0));
        assert_eq!(world.rolled_hands, vec![Hand::Mainhand; 3]);
    }

    #[test]
    fn armor_reduces_swing_damage() {
        let mut world = World::new();
        world.armor = 3731;
        let mut mh = AutoAttack::new(Hand::Mainhand);
        world.rolls.push_back(PhysicalAttackResult::Hit);
        let report = mh.perform(&mut world);
        let reduction = crate::mechanics::Mechanics::reduction_from_armor(3731, 60);
        assert_eq!(
            report.attack.damage,
            (285.714 * (1.0 - reduction)).round() as u32
        );
        assert_eq!(report.rage_gained, Some(8.9), "no damage term in the rage");
    }

    /// Two-handers generate 4.5 rage per second of base weapon speed; haste shortens the swing
    /// timer but not the rage of a swing.
    #[test]
    fn two_handers_and_hasted_swings() {
        let mut world = World::new();
        world.two_hand = true;
        world.mh_speed = 3.2;
        let mut mh = AutoAttack::new(Hand::Mainhand);
        world.rolls.push_back(PhysicalAttackResult::Hit);
        assert_eq!(mh.perform(&mut world).rage_gained, Some(14.4));

        world.haste = 1.3;
        world.rolls.push_back(PhysicalAttackResult::Hit);
        let report = mh.perform(&mut world);
        assert!((mh.next_expected_use(0.0) - 3.2 / 1.3).abs() < 1e-9);
        assert_eq!(report.rage_gained, Some(14.4), "base speed, not hasted");
        assert_eq!(world.rage.current_tenths(), 288);
    }

    /// A blocked swing lands less the target's block value; a block value covering the whole
    /// swing makes it a full block, which counts as avoided for the procs. Both give rage.
    #[test]
    fn blocked_swings_lose_the_block_value() {
        let mut world = World::new();
        let mut mh = AutoAttack::new(Hand::Mainhand);

        // No block value: a block is a hit (286), a block crit a crit (571).
        world.rolls.push_back(PhysicalAttackResult::Block);
        let report = mh.perform(&mut world);
        assert_eq!(report.attack.result, PhysicalAttackResult::Block);
        assert_eq!(report.attack.damage, 286);
        assert_eq!(report.proc_sources, vec![ProcSource::MainhandSwing]);
        world.rolls.push_back(PhysicalAttackResult::BlockCritical);
        let report = mh.perform(&mut world);
        assert_eq!(report.attack.damage, 571);
        assert_eq!(
            report.proc_sources,
            vec![ProcSource::MainhandSwing, ProcSource::MeleeCritical]
        );

        world.block_value = 50;
        world.rage.reset();
        world.rolls.push_back(PhysicalAttackResult::Block);
        let report = mh.perform(&mut world);
        assert_eq!(report.attack.damage, 236);
        assert_eq!(report.rage_gained, Some(8.9), "the swing's full rage");
        world.rolls.push_back(PhysicalAttackResult::BlockCritical);
        let report = mh.perform(&mut world);
        assert_eq!(report.attack.damage, 521);

        // Fully absorbed: no damage, the swing's rage, a full block for the procs.
        world.block_value = 300;
        world.rage.reset();
        world.rolls.push_back(PhysicalAttackResult::Block);
        let report = mh.perform(&mut world);
        assert_eq!(report.attack.result, PhysicalAttackResult::Block);
        assert_eq!(report.attack.damage, 0);
        assert_eq!(report.rage_gained, Some(8.9));
        assert_eq!(report.proc_sources, vec![ProcSource::MeleeFullBlock]);
    }

    #[test]
    fn avoided_swings_generate_no_rage_and_no_damage() {
        let mut world = World::new();
        let mut mh = AutoAttack::new(Hand::Mainhand);
        for (result, source) in [
            (PhysicalAttackResult::Dodge, ProcSource::MeleeDodge),
            (PhysicalAttackResult::Parry, ProcSource::MeleeParry),
        ] {
            world.rolls.push_back(result);
            let report = mh.perform(&mut world);
            assert_eq!(report.attack.result, result);
            assert_eq!(report.attack.damage, 0);
            assert_eq!(report.rage_gained, None, "{result:?}");
            assert_eq!(report.proc_sources, vec![source]);
        }

        world.rolls.push_back(PhysicalAttackResult::Miss);
        let report = mh.perform(&mut world);
        assert_eq!(report.rage_gained, None);
        assert_eq!(world.rage.current_tenths(), 0);
        assert_eq!(report.proc_sources, vec![ProcSource::MeleeMiss]);

        // Non-rage users never gain rage.
        world.rage_user = false;
        world.rolls.push_back(PhysicalAttackResult::Hit);
        assert_eq!(mh.perform(&mut world).rage_gained, None);
    }

    #[test]
    fn offhand_swings_apply_the_penalty() {
        let mut world = World::new();
        let mut oh = AutoAttack::new(Hand::Offhand);
        assert_eq!(oh.proc_source(), ProcSource::OffhandSwing);
        assert_eq!(oh.offhand_penalty(), 0.5);
        // (50 + 1.8 * 1000 / 14) * 0.5 = 89.29
        world.rolls.push_back(PhysicalAttackResult::Hit);
        let report = oh.perform(&mut world);
        assert_eq!(report.hand, Hand::Offhand);
        assert_eq!(report.attack.damage, 89);
        assert_eq!(report.proc_sources, vec![ProcSource::OffhandSwing]);
        // Half the one-hand rate: 1.73 × 1.8 = 3.114 rage.
        assert_eq!(report.rage_gained, Some(3.1));
        assert_eq!(world.reactions, 0);
        assert_eq!(oh.next_expected_use(0.0), 1.8);

        oh.set_offhand_penalty(0.625);
        world.rolls.push_back(PhysicalAttackResult::Hit);
        let report = oh.perform(&mut world);
        assert_eq!(report.attack.damage, 112);
        assert_eq!(
            report.rage_gained,
            Some(3.1),
            "damage does not change the rage"
        );

        // Dual Wield Specialization 5/5 (+100 %) brings it to the one-hand rate: 0.28 carried
        // + 62.28 tenths.
        world.offhand_rage_percent = 100;
        world.rolls.push_back(PhysicalAttackResult::Hit);
        assert_eq!(oh.perform(&mut world).rage_gained, Some(6.2));
        world.rolls.push_back(PhysicalAttackResult::Dodge);
        assert_eq!(oh.perform(&mut world).rage_gained, None);
    }

    #[test]
    fn swing_events_carry_increasing_iterations() {
        let mut world = World::new();
        let mut mh = AutoAttack::new(Hand::Mainhand);
        mh.schedule_next(&mut world);
        assert_eq!(mh.iteration(), 1);
        assert!(mh.attack_is_valid(1));
        assert!(!mh.attack_is_valid(0));
        assert_eq!(
            world.swing_events(),
            vec![(
                0.0,
                EventKind::MainhandMeleeHit {
                    character: CharId(1),
                    iteration: 1
                }
            )]
        );

        world.rolls.push_back(PhysicalAttackResult::Hit);
        mh.extra_attack(&mut world);
        assert_eq!(mh.iteration(), 2);
        assert!(!mh.attack_is_valid(1));
        let events = world.swing_events();
        assert_eq!(events.len(), 2);
        assert_eq!(events[1].0, 2.6);

        let mut oh = AutoAttack::new(Hand::Offhand);
        oh.schedule_next(&mut world);
        assert!(matches!(
            world.swing_events()[0].1,
            EventKind::MainhandMeleeHit { .. } | EventKind::OffhandMeleeHit { .. }
        ));
    }

    #[test]
    fn mid_swing_haste_changes_retime_the_swing() {
        let mut world = World::new();
        world.mh_speed = 2.0;
        let mut mh = AutoAttack::new(Hand::Mainhand);
        world.rolls.push_back(PhysicalAttackResult::Hit);
        mh.perform(&mut world);
        assert_eq!(mh.next_expected_use(0.0), 2.0);
        world.advance_to(1.0);
        mh.update_next_expected_use(1.0, 1.0);
        assert!((mh.next_expected_use(1.0) - 1.5).abs() < 1e-9);

        world.mh_speed = 1.5;
        let mut mh = AutoAttack::new(Hand::Mainhand);
        world.rolls.push_back(PhysicalAttackResult::Hit);
        mh.perform(&mut world);
        assert_eq!(mh.next_expected_use(1.0), 2.5);
        mh.update_next_expected_use(2.0, -1.0);
        assert!((mh.next_expected_use(2.0) - 3.0).abs() < 1e-9);

        // A swing already due is left alone, and never reported in the past.
        mh.update_next_expected_use(5.0, 1.0);
        assert_eq!(mh.next_expected_use(5.0), 5.0);
        assert_eq!(mh.time_until_next_swing(5.0), 0.0);
    }

    #[test]
    fn parry_haste_advances_the_swing() {
        let mut mh = AutoAttack::new(Hand::Mainhand);
        mh.complete_swing(10.0, 2.0);
        // More than 50% remaining: the swing lands at last_used + 60% of the speed.
        mh.update_next_expected_use_for_parry(10.5, 2.0);
        assert!((mh.next_expected_use(10.5) - 11.2).abs() < 1e-9);

        mh.complete_swing(10.0, 2.0);
        // Between 20% and 50% remaining: advanced by 20% of the speed.
        mh.update_next_expected_use_for_parry(11.2, 2.0);
        assert!((mh.next_expected_use(11.2) - 11.6).abs() < 1e-9);

        mh.complete_swing(10.0, 2.0);
        // Less than 20% remaining: unchanged.
        mh.update_next_expected_use_for_parry(11.8, 2.0);
        assert!((mh.next_expected_use(11.8) - 12.0).abs() < 1e-9);
    }

    #[test]
    fn reset_swing_timer_schedules_only_while_attacking() {
        let mut world = World::new();
        let mut mh = AutoAttack::new(Hand::Mainhand);
        world.advance_to(4.0);
        mh.reset_swing_timer_and_schedule(&mut world);
        assert_eq!(mh.next_expected_use(4.0), 6.6);
        assert_eq!(world.swing_events().len(), 1);
        assert_eq!(world.swing_events()[0].0, 6.6);

        world.attacking = false;
        mh.reset_swing_timer_and_schedule(&mut world);
        assert_eq!(world.swing_events().len(), 1);

        mh.prepare_set_of_combat_iterations();
        assert_eq!(mh.next_expected_use(0.0), 0.0);
        assert_eq!(mh.iteration(), 0);
    }
}
