//! Loads the fixture dump (`tests/fixtures/tables`, generated by `tests/fixtures/make_fixtures.py`
//! from build 1.60.1.70009) and checks the joins the exporters rely on. The expected values are
//! the ones quoted in `data/SPELL_INSTRUCTIONS.md` §1.8, `data/TALENT_INSTRUCTIONS.md` §1.7 and
//! `data/ITEM_INSTRUCTIONS.md` §1.4–1.9.

use std::path::{Path, PathBuf};

use csim_tables::tables::{ALL_TABLES, ItemDamageTable, SpellEffectRow, SpellNameRow};
use csim_tables::{TableDir, TableError, Tables};

const BUILD: &str = "1.60.1.70009";

fn fixtures() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/tables")
}

fn tables() -> Tables {
    Tables::load_dir(fixtures()).expect("fixture tables load")
}

/// A scratch directory under the target dir, removed when dropped.
struct Scratch(PathBuf);

impl Scratch {
    fn new(name: &str) -> Self {
        let dir = Path::new(env!("CARGO_TARGET_TMPDIR")).join(name);
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        Self(dir)
    }

    fn write(&self, file: &str, content: &str) {
        std::fs::write(self.0.join(file), content).unwrap();
    }
}

impl Drop for Scratch {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

#[test]
fn directory_detects_the_build_and_lists_every_table() {
    let dir = TableDir::open(fixtures()).unwrap();
    assert_eq!(dir.build(), BUILD);
    assert_eq!(
        TableDir::builds(fixtures()).unwrap(),
        vec![BUILD.to_owned()]
    );
    let names: Vec<&str> = dir.table_names().collect();
    assert_eq!(names.len(), ALL_TABLES.len());
    for table in ALL_TABLES {
        assert!(dir.has(table), "{table} missing from fixtures");
        assert!(
            dir.path(table)
                .unwrap()
                .ends_with(format!("{table}.{BUILD}.csv"))
        );
    }
    assert!(csim_tables::dir::missing_tables(&dir, ALL_TABLES.iter().copied()).is_empty());
    assert_eq!(dir.row_count("SpellShapeshiftForm").unwrap(), 3);
    assert_eq!(dir.columns("SpellName").unwrap(), ["ID", "Name_lang"]);
    assert!(matches!(
        dir.path("ItemExtendedCost"),
        Err(TableError::MissingTable { ref table, .. }) if table == "ItemExtendedCost"
    ));
}

#[test]
fn open_build_selects_a_build_and_rejects_unknown_ones() {
    let dir = TableDir::open_build(fixtures(), BUILD).unwrap();
    assert_eq!(dir.build(), BUILD);
    assert!(matches!(
        TableDir::open_build(fixtures(), "2.0.0.1"),
        Err(TableError::UnknownBuild { ref build, .. }) if build == "2.0.0.1"
    ));
}

#[test]
fn directory_errors_are_specific() {
    let missing = fixtures().join("does-not-exist");
    assert!(matches!(
        TableDir::open(&missing),
        Err(TableError::Io { ref dir, .. }) if *dir == missing
    ));

    let empty = Scratch::new("csim-tables-empty");
    empty.write("README.txt", "not a table");
    assert!(matches!(
        TableDir::open(&empty.0),
        Err(TableError::NoTables { .. })
    ));

    let two = Scratch::new("csim-tables-two-builds");
    two.write("SpellName.1.0.0.1.csv", "ID,Name_lang\n1,A\n");
    two.write("SpellName.1.0.0.2.csv", "ID,Name_lang\n1,B\n");
    assert!(matches!(
        TableDir::open(&two.0),
        Err(TableError::AmbiguousBuild { ref builds, .. })
            if builds == &["1.0.0.1".to_owned(), "1.0.0.2".to_owned()]
    ));
    let dir = TableDir::open_build(&two.0, "1.0.0.2").unwrap();
    let rows = dir.read::<SpellNameRow>().unwrap();
    assert_eq!(rows[0].name, "B");
    assert!(matches!(
        dir.read::<SpellEffectRow>(),
        Err(TableError::MissingTable { ref table, ref build, .. })
            if table == "SpellEffect" && build == "1.0.0.2"
    ));
}

#[test]
fn malformed_files_are_reported_with_context() {
    let bad = Scratch::new("csim-tables-bad");
    bad.write("SpellName.1.0.0.1.csv", "ID,Title\n1,A\n");
    bad.write(
        "SpellDuration.1.0.0.1.csv",
        "ID,Duration,MaxDuration,DurationPerResource\n1,ten,0,0\n",
    );
    bad.write(
        "SpellCastTimes.1.0.0.1.csv",
        "ID,Base,Minimum\n1,0,0\n2,0\n",
    );
    let dir = TableDir::open(&bad.0).unwrap();
    assert!(matches!(
        dir.read::<SpellNameRow>(),
        Err(TableError::MissingColumn { ref table, ref column }) if table == "SpellName" && column == "Name_lang"
    ));
    let err = dir
        .read::<csim_tables::tables::SpellDurationRow>()
        .unwrap_err();
    assert_eq!(
        err.to_string(),
        "SpellDuration line 2, column Duration: cannot parse \"ten\" as i32"
    );
    assert!(matches!(
        dir.read::<csim_tables::tables::SpellCastTimesRow>(),
        Err(TableError::Csv { .. })
    ));
}

#[test]
fn streaming_rows_reads_records_by_header_name() {
    let dir = TableDir::open(fixtures()).unwrap();
    let mut names = Vec::new();
    dir.for_each_row("SpellName", |row| {
        if row.field::<u32>("ID")? == 12294 {
            names.push(row.field::<String>("Name_lang")?);
        }
        Ok(())
    })
    .unwrap();
    assert_eq!(names, ["Mortal Strike"]);
    let kept = dir
        .read_where::<SpellNameRow>(|r| r.name.starts_with("Deep"))
        .unwrap();
    assert_eq!(kept.len(), 3, "Deep Wounds x2 and Deep Wound");
}

#[test]
fn mortal_strike_joins_every_spell_table() {
    let t = tables();
    assert_eq!(t.build(), BUILD);
    let id = 12294;
    assert!(t.spell_exists(id));
    assert!(!t.spell_exists(1));
    assert_eq!(t.spell_name(id), Some("Mortal Strike"));
    assert_eq!(t.spell(id).unwrap().name_subtext, "Rank 1");

    let misc = t.spell_misc(id).unwrap();
    assert_eq!(misc.attributes[0], 0x50010);
    assert_eq!(misc.school_mask, 1);
    assert_eq!(
        t.spell_duration(misc.duration_index).unwrap().duration,
        10_000
    );
    assert_eq!(t.spell_cast_times(misc.casting_time_index).unwrap().base, 0);
    assert_eq!(t.spell_range(misc.range_index).unwrap().range_max[0], 5.0);

    let effects = t.spell_effects(id);
    assert_eq!(effects.len(), 2);
    assert_eq!(
        (
            effects[0].effect_index,
            effects[0].effect,
            effects[0].effect_aura
        ),
        (0, 6, 118)
    );
    assert_eq!(effects[0].effect_base_points, -50.0);
    assert_eq!(effects[0].effect_misc_value, [127, 0]);
    assert_eq!(effects[0].implicit_target, [6, 0]);
    assert_eq!((effects[1].effect_index, effects[1].effect), (1, 121));
    assert_eq!(effects[1].effect_base_points, 85.0);

    let power = t.spell_power(id);
    assert_eq!(power.len(), 1);
    assert_eq!((power[0].power_type, power[0].mana_cost), (1, 300));
    assert_eq!(t.power_type(1).unwrap().display_modifier, 10);
    assert_eq!(t.power_type(1).unwrap().max_base_power, 1000);

    let cd = t.spell_cooldowns(id).unwrap();
    assert_eq!(
        (
            cd.recovery_time,
            cd.category_recovery_time,
            cd.start_recovery_time
        ),
        (0, 6000, 1500)
    );
    let cat = t.spell_categories(id).unwrap();
    assert_eq!(
        (cat.category, cat.defense_type, cat.start_recovery_category),
        (971, 2, 133)
    );
    assert_eq!(t.spell_category(971).unwrap().name, "Mortal Strike");
    assert_eq!(t.spell_category(133).unwrap().name, "Global");

    let levels = t.spell_levels(id).unwrap();
    assert_eq!(
        (levels.base_level, levels.spell_level, levels.max_level),
        (40, 40, 0)
    );
    let class = t.spell_class_options(id).unwrap();
    assert_eq!(class.spell_class_set, 4);
    assert_eq!(class.spell_class_mask, [33554432, 0, 0, 0]);
    let equip = t.spell_equipped_items(id).unwrap();
    assert_eq!(
        (equip.equipped_item_class, equip.equipped_item_subclass),
        (2, 173555)
    );
    assert!(t.spell_shapeshift(id).is_none());
    assert!(t.spell_aura_options(id).is_none());
    assert!(t.spell_labels(id).contains(&25));

    let abilities: Vec<_> = t.skill_line_abilities_of_spell(id).collect();
    assert_eq!(abilities.len(), 1);
    assert_eq!((abilities[0].skill_line, abilities[0].class_mask), (26, 1));
}

#[test]
fn deep_wounds_and_flurry_link_procs_to_their_payloads() {
    let t = tables();
    let deep_wounds = t.spell_effects(12834);
    assert_eq!((deep_wounds[0].effect, deep_wounds[0].effect_aura), (6, 42));
    assert_eq!(deep_wounds[0].effect_trigger_spell, 12162);
    assert_eq!(t.spell_name(12162), Some("Deep Wounds"));
    assert_eq!(t.spell_effects(12162)[0].effect, 3);
    let aura = t.spell_aura_options(12834).unwrap();
    assert_eq!((aura.proc_chance, aura.proc_type_mask[0]), (100, 0x11154));
    assert_eq!(
        t.spell_misc(12834).unwrap().attributes[0] & 0x40,
        0x40,
        "passive"
    );
    assert_eq!(t.spell_categories(12162).unwrap().mechanic, 15, "bleed");
    assert_eq!(
        t.spell_duration(t.spell_misc(412609).unwrap().duration_index)
            .unwrap()
            .duration,
        12_000
    );

    let flurry_buff = t.spell_aura_options(12966).unwrap();
    assert_eq!(
        (flurry_buff.proc_charges, flurry_buff.proc_type_mask[0]),
        (3, 0x4)
    );
    let haste = &t.spell_effects(12966)[0];
    assert_eq!((haste.effect_aura, haste.effect_base_points), (319, 30.0));
    assert_eq!(
        t.spell_aura_options(12319).unwrap().proc_type_mask[0],
        0x15554
    );

    let rend = &t.spell_effects(11574)[0];
    assert_eq!(
        (
            rend.effect_aura,
            rend.effect_base_points,
            rend.effect_aura_period
        ),
        (3, 21.0, 3000)
    );

    let bloodrage = t.spell_effects(2687);
    assert_eq!(
        (
            bloodrage[0].effect,
            bloodrage[0].effect_base_points,
            bloodrage[0].effect_misc_value[0]
        ),
        (30, 100.0, 1)
    );
    assert_eq!(
        (bloodrage[1].effect, bloodrage[1].effect_trigger_spell),
        (64, 29131)
    );
    assert_eq!(t.spell_power(2687)[0].power_type, -2, "health cost");
    assert_eq!(t.spell_power(2687)[0].power_cost_pct, 20.0);
    let tick = &t.spell_effects(29131)[0];
    assert_eq!(
        (
            tick.effect_aura,
            tick.effect_base_points,
            tick.effect_aura_period
        ),
        (24, 10.0, 1000)
    );
}

#[test]
fn restrictions_masks_and_variance_are_read() {
    let t = tables();
    let execute = 5308;
    assert_eq!(
        t.spell_aura_restrictions(execute)
            .unwrap()
            .target_aura_state,
        2
    );
    assert_eq!(
        t.spell_shapeshift(execute).unwrap().shapeshift_mask[0],
        327680
    );
    let e0 = &t.spell_effects(execute)[0];
    assert_eq!(e0.effect, 3);
    assert!((e0.effect_chain_amplitude - 0.3).abs() < 1e-6);
    assert_eq!(t.spell_effects(execute)[1].effect_trigger_spell, 26651);
    let note = &t.spell(26651).unwrap().description;
    assert!(note.starts_with("Designer Note:"), "quoted multi-line cell");
    assert_eq!(note.lines().count(), 3);

    let revenge = 25288;
    assert_eq!(
        t.spell_aura_restrictions(revenge)
            .unwrap()
            .caster_aura_state,
        1
    );
    assert!((t.spell_effects(revenge)[0].variance - 0.2).abs() < 1e-6);
    assert_eq!(t.spell_categories(revenge).unwrap().category, 65);
    assert_eq!(t.spell_category(65).unwrap().name, "Melee (Special)");
    let revenge_ability = t.skill_line_abilities_of_spell(revenge).next().unwrap();
    assert_eq!(revenge_ability.supercedes_spell, 11601);

    let whirlwind = 1680;
    assert_eq!(
        t.spell_target_restrictions(whirlwind).unwrap().max_targets,
        4
    );
    assert_eq!(
        t.spell_class_options(whirlwind).unwrap().spell_class_mask,
        [0x8000_0000, 4, 0, 0],
        "signed CSV masks become bit patterns"
    );
    assert_eq!(t.spell_radius(14).unwrap().radius, 8.0);

    let berserker = &t.spell_effects(2458)[0];
    assert_eq!(
        (berserker.effect_aura, berserker.effect_misc_value[0]),
        (36, 19)
    );
    assert_eq!(
        t.spell_shapeshift_form(19).unwrap().name,
        "Berserker Stance"
    );
    assert_eq!(t.spell_shapeshift_form(19).unwrap().preset_spell_id, [0; 8]);
    let passive: Vec<_> = t
        .spell_effects(7381)
        .iter()
        .map(|e| (e.effect_aura, e.effect_base_points))
        .collect();
    assert_eq!(passive, [(290, 3.0), (87, 10.0), (10, -20.0), (166, 0.0)]);

    let improved_hs = &t.spell_effects(12282)[0];
    assert_eq!(
        (
            improved_hs.effect_aura,
            improved_hs.effect_misc_value[0],
            improved_hs.effect_base_points
        ),
        (107, 14, -10.0)
    );
    assert_eq!(improved_hs.effect_spell_class_mask, [64, 0, 0, 0]);
    assert_eq!(t.spell_class_options(78).unwrap().spell_class_mask[0], 64);
    assert_eq!(
        t.spell_misc(78).unwrap().attributes[0] & 0x4,
        0x4,
        "on next swing"
    );
}

#[test]
fn skill_lines_give_the_spellbook_and_rank_chains() {
    let t = tables();
    assert_eq!(t.skill_line(26).unwrap().display_name, "Arms");
    assert_eq!(t.skill_line(26).unwrap().category_id, 7);
    assert_eq!(t.skill_line(125).unwrap().category_id, 9);
    assert_eq!(t.skill_lines().count(), 4);

    let warrior_lines: Vec<u32> = t
        .skill_race_class_info()
        .iter()
        .filter(|r| r.class_mask & 1 != 0 && t.skill_line(r.skill_id).unwrap().category_id == 7)
        .map(|r| r.skill_id)
        .collect();
    assert_eq!(warrior_lines.len(), 3);
    let racial = t
        .skill_race_class_info()
        .iter()
        .find(|r| r.skill_id == 125)
        .unwrap();
    assert_eq!((racial.class_mask, racial.race_masks[0]), (1503, 2));
    let all_races = t
        .skill_race_class_info()
        .iter()
        .find(|r| r.skill_id == 26)
        .unwrap();
    assert_eq!(all_races.race_masks, [u32::MAX, u32::MAX]);

    let arms: Vec<u32> = t.skill_line_abilities(26).map(|a| a.spell).collect();
    assert!(arms.contains(&78) && arms.contains(&12294) && arms.contains(&12834));
    let hs2 = t.skill_line_abilities_of_spell(284).next().unwrap();
    assert_eq!(hs2.supercedes_spell, 78);
    let hs1 = t.skill_line_abilities_of_spell(78).next().unwrap();
    assert_eq!((hs1.supercedes_spell, hs1.acquire_method), (0, 2));
    let talent = t.skill_line_abilities_of_spell(12834).next().unwrap();
    assert_eq!(talent.class_mask, 0, "talent-granted");
    let blood_fury = t.skill_line_abilities_of_spell(20572).next().unwrap();
    assert_eq!((blood_fury.skill_line, blood_fury.race_masks[0]), (125, 2));
    assert_eq!(t.skill_line_x_trait_tree()[0].trait_tree_id, 1117);
}

#[test]
fn trait_tables_give_talent_ranks_prerequisites_and_tiers() {
    let t = tables();
    assert!(t.trait_tree(1117).is_some());
    assert_eq!(
        t.trait_nodes_of_tree(1117),
        [105941, 105945, 105950, 105956]
    );

    let node = t.trait_node(105950).unwrap();
    assert_eq!((node.pos_x, node.pos_y), (2220, 3330));
    let entries = t.trait_node_entries_of_node(105950);
    assert_eq!(entries.len(), 1);
    let entry = t.trait_node_entry(entries[0]).unwrap();
    assert_eq!(entry.max_ranks, 3);
    let definition = t.trait_definition(entry.trait_definition_id).unwrap();
    assert_eq!(definition.spell_id, 12834);
    let points = t.trait_definition_effect_points(definition.id);
    assert_eq!(points.len(), 1);
    assert_eq!((points[0].effect_index, points[0].operation_type), (0, 0));
    assert!(t.curve(points[0].curve_id).is_some());
    let values: Vec<f32> = t
        .curve_points(points[0].curve_id)
        .iter()
        .map(|p| p.pos[1])
        .collect();
    assert_eq!(values, [20.0, 40.0, 60.0]);
    assert_eq!(t.trait_prerequisites(105950), [105956]);
    assert_eq!(t.trait_prerequisites(105941), [105945]);
    assert!(t.trait_prerequisites(105956).is_empty());
    assert_eq!(t.trait_edges().len(), 2);

    let mortal_strike_entry = t.trait_node_entries_of_node(105941)[0];
    let ms_definition = t
        .trait_node_entry(mortal_strike_entry)
        .unwrap()
        .trait_definition_id;
    assert_eq!(t.trait_definition(ms_definition).unwrap().spell_id, 12294);
    assert!(t.trait_definition_effect_points(ms_definition).is_empty());

    // Tab: the group with display info maps to the Arms skill line.
    let tab = t
        .trait_groups_of_node(105950)
        .iter()
        .find_map(|&g| t.trait_group_display_info(g))
        .unwrap();
    assert_eq!(tab.skill_line_id, 26);
    assert_eq!(t.trait_nodes_of_group(tab.trait_node_group_id).len(), 4);
    assert!(t.trait_node_group(tab.trait_node_group_id).is_some());

    // Tier gate: Deep Wounds sits in a group whose condition requires 10 points spent.
    let required: Vec<u32> = t
        .trait_groups_of_node(105950)
        .iter()
        .flat_map(|&g| t.trait_conds_of_group(g))
        .map(|&c| t.trait_cond(c).unwrap().spent_amount_required)
        .collect();
    assert_eq!(required, [10]);
    let mortal_strike_gate: Vec<u32> = t
        .trait_groups_of_node(105941)
        .iter()
        .flat_map(|&g| t.trait_conds_of_group(g))
        .map(|&c| t.trait_cond(c).unwrap().spent_amount_required)
        .collect();
    assert_eq!(mortal_strike_gate, [30]);

    assert_eq!(t.trait_currency(3820).unwrap().sourced_max, 51);
    assert_eq!(t.trait_currency_sources()[0].player_level, 10);
}

#[test]
fn class_and_race_rows_are_read() {
    let t = tables();
    let warrior = t.chr_class(1).unwrap();
    assert_eq!(
        (
            warrior.filename.as_str(),
            warrior.spell_class_set,
            warrior.display_power
        ),
        ("WARRIOR", 4, 1)
    );
    assert_eq!(warrior.attack_power_per_strength, 2.0);
    assert_eq!(t.chr_classes().count(), 1);
    let orc = t.chr_race(2).unwrap();
    assert_eq!(
        (orc.name.as_str(), orc.alliance, orc.playable_race_bit),
        ("Orc", 1, 1)
    );
    assert_eq!(t.chr_race(1).unwrap().client_file_string, "Human");
    assert_eq!(t.chr_races().count(), 2);
    assert_eq!(
        t.power_type(4).unwrap().name_global_string_tag,
        "COMBO_POINTS"
    );
    assert!(t.power_type(99).is_none());
    assert_eq!(
        t.spell_ids().count(),
        42,
        "25 Warrior spells + 17 item and set spells"
    );
    assert!(t.spell_class_options_iter().all(|c| c.spell_class_set == 4));
}

/// The (bonusStat, budget share) pairs of an item.
fn item_stats(t: &Tables, item_id: u32) -> Vec<(i32, i32)> {
    let sparse = t.item_sparse(item_id).unwrap();
    sparse
        .stat_modifier_bonus_stat
        .iter()
        .zip(&sparse.stat_percent_editor)
        .filter(|(stat, _)| **stat >= 0)
        .map(|(&stat, &pct)| (stat, pct))
        .collect()
}

#[test]
fn item_rows_give_identity_stats_and_budgets() {
    let t = tables();
    // Thunderfury: ITEM_INSTRUCTIONS §1.4 worked example.
    let item = t.item(19019).unwrap();
    assert_eq!(
        (item.class_id, item.subclass_id, item.inventory_type),
        (2, 7, 13)
    );
    assert_eq!(t.item_sub_class(2, 7).unwrap().display_name, "Sword");
    let sparse = t.item_sparse(19019).unwrap();
    assert_eq!(sparse.name, "Thunderfury, Blessed Blade of the Windseeker");
    assert_eq!(
        (
            sparse.item_level,
            sparse.required_level,
            sparse.overall_quality_id,
            sparse.bonding,
            sparse.max_count
        ),
        (80, 60, 5, 1, 1)
    );
    assert_eq!((sparse.item_delay, sparse.damage_type), (1900, 0));
    assert!((sparse.dmg_variance - 0.6).abs() < 1e-6);
    assert_eq!(sparse.allowable_class, -1);
    assert_eq!(sparse.allowable_race, [u32::MAX, u32::MAX]);
    assert_eq!(
        item_stats(&t, 19019),
        [(3, 2174), (7, 3478), (51, 3478), (55, 3913)]
    );
    assert_eq!(t.rand_prop_points(80).unwrap().epic[3], 23);

    // Lionheart Helm: head, epic, Epic_0[61] = 45.
    let mut lionheart = item_stats(&t, 12640);
    lionheart.sort_unstable();
    assert_eq!(lionheart, [(4, 4000), (31, 4444), (32, 6222)]);
    assert_eq!(t.rand_prop_points(61).unwrap().epic[0], 45);
    // AQ40 ranged weapons use the fifth column.
    assert_eq!(t.item_sparse(21616).unwrap().item_level, 78);
    assert_eq!(t.rand_prop_points(78).unwrap().epic[4], 17);

    // Items the dump has no ItemSparse row for still have their Item row.
    assert!(t.item(11815).is_some());
    assert!(t.item_sparse(11815).is_none());
    assert!(t.item(1).is_none());
    assert_eq!(t.items().count(), 24);
    assert_eq!(t.item_sparse_rows().count(), 23);
}

#[test]
fn armor_and_damage_tables_are_keyed_by_item_level() {
    let t = tables();
    let total = t.item_armor_total(1).unwrap();
    assert!((total.cloth - 18.52).abs() < 1e-3);
    assert!((total.plate - 271.58).abs() < 1e-2);
    assert!((t.item_armor_quality(1).unwrap().quality_mod[4] - 1.2).abs() < 1e-6);
    assert_eq!(t.item_armor_shield(1).unwrap().quality[4], 38.0);
    let waist = t.armor_location(6).unwrap();
    assert!((waist.plate_modifier - 0.09).abs() < 1e-6);
    assert_eq!(t.armor_location(20).unwrap().plate_modifier, 0.0);
    assert!(
        (t.item_damage(ItemDamageTable::OneHand, 72).unwrap().quality[4] - 53.516).abs() < 1e-3
    );
    for table in ItemDamageTable::ALL {
        assert!(t.item_damage(table, 60).is_some(), "{}", table.table());
    }
    assert!(t.item_damage(ItemDamageTable::Wand, 0).is_none());
}

#[test]
fn item_effects_sets_limits_and_suffixes_are_joined() {
    let t = tables();
    // Chance on hit, on use and on equip.
    let thunderfury: Vec<(u32, u32)> = t
        .item_effects_of_item(19019)
        .map(|e| (e.trigger_type, e.spell_id))
        .collect();
    assert_eq!(thunderfury, [(2, 21992)]);
    let earthstrike = t.item_effects_of_item(21180).next().unwrap();
    assert_eq!(
        (
            earthstrike.trigger_type,
            earthstrike.spell_id,
            earthstrike.cooldown_ms,
            earthstrike.spell_category_id,
            earthstrike.category_cooldown_ms
        ),
        (0, 25891, 120_000, 1141, 20_000)
    );
    let force_reactive_disk: Vec<(u32, u32)> = t
        .item_effects_of_item(18168)
        .map(|e| (e.legacy_slot_index, e.spell_id))
        .collect();
    assert_eq!(force_reactive_disk, [(0, 22618), (1, 22620)]);
    assert_eq!(
        t.item_effects_of_item(19406).count(),
        0,
        "Drake Fang Talisman: stats only"
    );
    // Hand of Justice has its effect even without an ItemSparse row.
    assert_eq!(
        t.item_effects_of_item(11815)
            .map(|e| (e.trigger_type, e.spell_id))
            .collect::<Vec<_>>(),
        [(1, 15600)]
    );
    assert_eq!(t.item_effect(101091).unwrap().spell_id, 21992);

    // Battlegear of Might (§1.8) and a set with a gap in its member list.
    let might = t.item_set(209).unwrap();
    assert_eq!(might.name, "Battlegear of Might");
    assert_eq!(might.item_ids.iter().filter(|&&i| i != 0).count(), 8);
    let bonuses: Vec<(u32, u32)> = t
        .item_set_spells(209)
        .iter()
        .map(|b| (b.threshold, b.spell_id))
        .collect();
    assert_eq!(bonuses, [(3, 23562), (5, 21838), (8, 23561)]);
    assert_eq!(t.item_sparse(21331).unwrap().item_set, 496);
    assert!(t.item_set(496).unwrap().item_ids.contains(&21330));
    assert_eq!(t.item_sets().count(), 3);
    assert!(t.item_set_spells(1).is_empty());

    // Unique-equipped group.
    let arena_master = t.item_sparse(18706).unwrap();
    let limit = t.item_limit_category(arena_master.limit_category).unwrap();
    assert_eq!((limit.name.as_str(), limit.quantity), ("Arena Master", 1));

    // Random suffixes: one tree, one node per suffix, stats + a name.
    assert_eq!(t.item_bonus_trees(8210), [5655]);
    assert!(t.item_bonus_trees(19019).is_empty());
    let nodes = t.item_bonus_tree_nodes(5655);
    assert_eq!(nodes.len(), 35);
    let eagle: Vec<(u32, i32, i32)> = t
        .item_bonuses(nodes[0].child_item_bonus_list_id)
        .iter()
        .map(|b| (b.bonus_type, b.value[0], b.value[1]))
        .collect();
    assert_eq!(eagle, [(2, 5, 6666), (2, 7, 6666), (5, 14300, 0)]);
    assert_eq!(
        t.item_name_description(14300).unwrap().description,
        "of the Eagle"
    );
}

mod export {
    use super::{BUILD, fixtures};
    use csim_engine::faction::PlayerClass;
    use csim_engine::spell::dbc::{AuraType, PowerType, SpellEffectName};
    use csim_engine::spell::overrides::{Overrides, SpellOverride};
    use csim_engine::spell::record::SpellDb;
    use csim_tables::Tables;
    use csim_tables::export::{self, spells};

    fn tables() -> Tables {
        Tables::load_dir(fixtures()).unwrap()
    }

    #[test]
    fn class_walk_finds_lines_talents_and_hidden_payloads() {
        let t = tables();
        assert_eq!(spells::chr_class_id(&t, PlayerClass::Warrior).unwrap(), 1);
        assert!(matches!(
            spells::chr_class_id(&t, PlayerClass::Rogue),
            Err(export::ExportError::UnknownClass(_))
        ));
        assert_eq!(
            spells::class_skill_lines(&t, PlayerClass::Warrior).unwrap(),
            [26, 256, 257]
        );
        assert_eq!(
            spells::talent_spells(&t, PlayerClass::Warrior).unwrap(),
            [12286, 12292, 12294, 12834]
        );

        let file = export::export_class(&t, PlayerClass::Warrior, &Overrides::new()).unwrap();
        assert_eq!(file.build, BUILD);
        assert_eq!(file.class, Some(PlayerClass::Warrior));
        let ids: Vec<u32> = file.spells.iter().map(|s| s.id).collect();
        assert!(ids.windows(2).all(|w| w[0] < w[1]), "sorted by id");
        assert!(ids.contains(&12294), "skill line ability");
        assert!(ids.contains(&12162), "trigger of Deep Wounds");
        assert!(ids.contains(&26651), "trigger of Execute");
        assert!(ids.contains(&29131), "trigger of Bloodrage");
        assert!(!ids.contains(&20572), "racial is not a class spell");
        assert!(!ids.contains(&412609), "only reached through an override");
        assert!(ids.contains(&7381), "stance passive sits in skill line 256");
        assert!(ids.contains(&694), "Mocking Blow keeps its damage");
        assert!(
            !ids.contains(&355),
            "Taunt is pruned: ATTACK_ME + MOD_TAUNT"
        );
        assert!(
            !ids.contains(&5246),
            "Intimidating Shout: fear, speed and a stun trigger"
        );
        assert!(!ids.contains(&20511), "the stun itself");
        let (_, report) =
            export::export_class_with_report(&t, PlayerClass::Warrior, &Overrides::new()).unwrap();
        assert_eq!(
            report.spell_names(),
            [
                "Taunt (355)",
                "Intimidating Shout (5246)",
                "Intimidating Shout (20511)"
            ]
        );
        assert!(
            report
                .effects
                .iter()
                .any(|e| e.spell == 694 && e.what == "aura UNKNOWN_11")
        );

        let mut overrides = Overrides::new();
        let mut stance = SpellOverride::new(2458);
        stance.stance_passive = Some(412609);
        overrides.add(stance).unwrap();
        let with_overrides = export::export_class(&t, PlayerClass::Warrior, &overrides).unwrap();
        assert_eq!(with_overrides.spells.len(), file.spells.len() + 1);
        assert!(with_overrides.spells.iter().any(|s| s.id == 412609));
    }

    #[test]
    fn records_carry_the_joined_columns() {
        let t = tables();
        let file = export::export_class(&t, PlayerClass::Warrior, &Overrides::new()).unwrap();
        let ms = file.spells.iter().find(|s| s.id == 12294).unwrap();
        assert_eq!(ms.name, "Mortal Strike");
        assert_eq!(ms.rank_text, "Rank 1");
        assert_eq!(ms.skill_line, Some(26));
        assert_eq!(ms.class_mask, 1, "a talent ability, yet flagged trainable");
        assert_eq!(ms.attributes[0], 0x50010);
        assert_eq!(ms.duration_ms, Some(10_000));
        assert_eq!(ms.range_yd, 5.0);
        assert_eq!(ms.power[0].power_type, PowerType::Rage);
        assert_eq!(ms.power[0].cost, 300);
        assert_eq!(ms.cooldown.category_recovery_ms, 6000);
        assert_eq!(ms.cooldown.start_recovery_ms, 1500);
        assert_eq!(ms.categories.category, 971);
        assert_eq!(ms.levels.base, 40);
        assert_eq!(ms.class_options.unwrap().mask, [33554432, 0, 0, 0]);
        assert_eq!(ms.equipped_items.unwrap().subclass_mask, 173555);
        assert_eq!(ms.labels, [25]);
        assert!(ms.description.contains("$s1"));
        // The MOD_HEALING_PCT aura (effect 0) is pruned; the damage keeps its table index.
        assert_eq!(ms.effects.len(), 1);
        assert_eq!(ms.effects[0].index, 1);
        assert_eq!(ms.effects[0].effect, SpellEffectName::NormalizedWeaponDmg);
        assert_eq!(ms.effects[0].base_points, 85.0);
        let unpruned = spells::record(&t, 12294, None);
        assert_eq!(unpruned.effects.len(), 2);
        assert_eq!(
            unpruned.effects[0].aura,
            AuraType::Unknown(118),
            "MOD_HEALING_PCT"
        );
        assert_eq!(unpruned.effects[0].misc_value, [127, 0]);

        let hs2 = file.spells.iter().find(|s| s.id == 284).unwrap();
        assert_eq!(hs2.supercedes, 78);
        assert_eq!(hs2.class_mask, 1);
        assert!(hs2.is_on_next_swing());
        let payload = file.spells.iter().find(|s| s.id == 12162).unwrap();
        assert_eq!(payload.skill_line, None);
        assert!(payload.is_hidden());
        let execute = file.spells.iter().find(|s| s.id == 5308).unwrap();
        assert!((execute.effects[0].chain_amplitude - 0.3).abs() < 1e-6);
        assert_eq!(execute.shapeshift_mask, 327680);
        let whirlwind = file.spells.iter().find(|s| s.id == 1680).unwrap();
        assert_eq!(whirlwind.max_targets, 4);
        assert_eq!(
            whirlwind.effects[0].radius_yd,
            [0.0, 8.0],
            "second radius slot"
        );
        let flurry_buff = file.spells.iter().find(|s| s.id == 12966).unwrap();
        assert_eq!(flurry_buff.aura_options.proc_charges, 3);
        assert_eq!(flurry_buff.aura_options.proc_type_mask.bits(), 0x4);
    }

    #[test]
    fn racial_walk_uses_the_race_masks() {
        let t = tables();
        assert_eq!(spells::racial_skill_lines(&t).unwrap(), [125]);
        let file = export::export_racials(&t, &Overrides::new()).unwrap();
        assert_eq!(file.class, None);
        let blood_fury = file.spells.iter().find(|s| s.id == 20572).unwrap();
        assert_eq!(blood_fury.race_mask, 2);
        assert_eq!(blood_fury.skill_line, Some(125));
        assert_eq!(blood_fury.cooldown.recovery_ms, 120_000);
    }

    #[test]
    fn rendered_files_load_back_through_the_engine() {
        let t = tables();
        let file = export::export_class(&t, PlayerClass::Warrior, &Overrides::new()).unwrap();
        let yaml = export::render(&file, "export-spells --class warrior").unwrap();
        assert!(yaml.starts_with("# Generated by `csim-tables export-spells --class warrior`"));
        assert!(yaml.contains("attributes: [327696, 134218240, 0, 1024, "));
        assert!(yaml.contains("implicit_target: [UNIT_TARGET_ENEMY, NONE]"));
        assert!(yaml.contains("effect: NORMALIZED_WEAPON_DMG"));
        let back: csim_engine::spell::record::SpellFile = serde_yaml::from_str(&yaml).unwrap();
        assert_eq!(back, file);

        let dir = std::path::Path::new(env!("CARGO_TARGET_TMPDIR")).join("csim-tables-export");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("warrior.yaml"), &yaml).unwrap();
        let racials = export::export_racials(&t, &Overrides::new()).unwrap();
        std::fs::write(
            dir.join("racials.yaml"),
            export::render(&racials, "export-spells --racials").unwrap(),
        )
        .unwrap();
        let db = SpellDb::load(&dir).unwrap();
        assert_eq!(db.len(), file.spells.len() + racials.spells.len());
        assert_eq!(db.rank_chain(284), [78, 284]);
        let unsupported: Vec<u32> = db.unsupported().iter().map(|u| u.spell).collect();
        assert_eq!(
            unsupported,
            [5308, 12162, 12292, 12319, 26651],
            "DUMMY effects without scripts"
        );
        std::fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn talent_export_joins_nodes_tabs_tiers_edges_and_curves() {
        let t = tables();
        assert_eq!(export::trait_tree(&t, PlayerClass::Warrior).unwrap(), 1117);
        let (file, report) = export::export_talents_with_report(&t, PlayerClass::Warrior).unwrap();
        assert!(report.is_empty(), "{report:?}");
        assert_eq!(file.build, "1.60.1.70009");
        assert_eq!(file.class, PlayerClass::Warrior);
        assert_eq!(
            (file.tree, file.points, file.points_per_tier),
            (1117, 51, 5)
        );
        assert_eq!(
            file.tabs.len(),
            1,
            "the fixture only has the Arms tab group"
        );
        assert_eq!(
            (file.tabs[0].skill_line, file.tabs[0].name.as_str()),
            (26, "Arms")
        );

        // Sorted by tier; the fixture's leftmost column is 1620 (Deep Wounds sits at 2220).
        type Summary<'a> = (u32, u32, &'a str, u32, u32, u32, Option<u32>);
        let summary: Vec<Summary> = file
            .talents
            .iter()
            .map(|t| {
                (
                    t.node,
                    t.spell,
                    t.name.as_str(),
                    t.tier,
                    t.column,
                    t.max_ranks,
                    t.requires,
                )
            })
            .collect();
        assert_eq!(
            summary,
            [
                (105956, 12286, "Improved Rend", 0, 1, 3, None),
                (105950, 12834, "Deep Wounds", 2, 1, 3, Some(105956)),
                (105945, 12292, "Sweeping Strikes", 4, 0, 1, None),
                (105941, 12294, "Mortal Strike", 6, 0, 1, Some(105945)),
            ]
        );
        let deep_wounds = file.talent(105950).unwrap();
        assert_eq!(deep_wounds.rank_values[&0], [20.0, 40.0, 60.0]);
        assert!(file.talent(105941).unwrap().rank_values.is_empty());

        let yaml = export::render_talents(&file, "export-talents --class warrior").unwrap();
        assert!(yaml.starts_with("# Generated by `csim-tables export-talents --class warrior`"));
        assert!(yaml.contains(
            "    0: [20.0, 40.0, 60.0]
"
        ));
        let back: csim_engine::talent::TalentFile = serde_yaml::from_str(&yaml).unwrap();
        assert_eq!(back, file);
        back.validate().unwrap();

        assert!(matches!(
            export::export_talents(&t, PlayerClass::Rogue),
            Err(export::ExportError::UnknownClass(_))
        ));
    }
}
