//! `SpellEffect.EffectAura`: the aura applied by an `APPLY_AURA`-family effect.

use super::dbc_enum;

dbc_enum! {
    /// Retail `AuraType`, the `EffectAura` column of `SpellEffect`.
    ///
    /// The engine interprets the values listed in `data/SPELL_INSTRUCTIONS.md` §1.7 (the ones with
    /// a doc comment below say how); the rest are named for reporting and are no-ops.
    AuraType: u32 {
        None = 0 => "NONE",
        BindSight = 1 => "BIND_SIGHT",
        ModPossess = 2 => "MOD_POSSESS",
        /// Bleed / DoT tick (`EffectAuraPeriod` ms), Rend.
        PeriodicDamage = 3 => "PERIODIC_DAMAGE",
        /// Scripted; what it does is in the description and in `data/spells/overrides/*.yaml`.
        Dummy = 4 => "DUMMY",
        ModConfuse = 5 => "MOD_CONFUSE",
        ModCharm = 6 => "MOD_CHARM",
        ModFear = 7 => "MOD_FEAR",
        PeriodicHeal = 8 => "PERIODIC_HEAL",
        ModAttackspeed = 9 => "MOD_ATTACKSPEED",
        /// Threat done %, misc = school mask (stance passives, Defiance).
        ModThreat = 10 => "MOD_THREAT",
        ModTaunt = 11 => "MOD_TAUNT",
        ModStun = 12 => "MOD_STUN",
        ModDamageDone = 13 => "MOD_DAMAGE_DONE",
        ModDamageTaken = 14 => "MOD_DAMAGE_TAKEN",
        DamageShield = 15 => "DAMAGE_SHIELD",
        ModStealth = 16 => "MOD_STEALTH",
        ModStealthDetect = 17 => "MOD_STEALTH_DETECT",
        ModInvisibility = 18 => "MOD_INVISIBILITY",
        ModInvisibilityDetect = 19 => "MOD_INVISIBILITY_DETECT",
        ObsModHealth = 20 => "OBS_MOD_HEALTH",
        ObsModPower = 21 => "OBS_MOD_POWER",
        /// Resistance, misc 1 = armor (Sunder Armor −450).
        ModResistance = 22 => "MOD_RESISTANCE",
        PeriodicTriggerSpell = 23 => "PERIODIC_TRIGGER_SPELL",
        /// Periodic resource gain, misc = power type (Bloodrage 1 rage/s).
        PeriodicEnergize = 24 => "PERIODIC_ENERGIZE",
        ModPacify = 25 => "MOD_PACIFY",
        ModRoot = 26 => "MOD_ROOT",
        ModSilence = 27 => "MOD_SILENCE",
        ReflectSpells = 28 => "REFLECT_SPELLS",
        /// Stat, misc −1 all / 0 Str / 1 Agi / 2 Sta / 3 Int / 4 Spi.
        ModStat = 29 => "MOD_STAT",
        ModSkill = 30 => "MOD_SKILL",
        ModIncreaseSpeed = 31 => "MOD_INCREASE_SPEED",
        ModIncreaseMountedSpeed = 32 => "MOD_INCREASE_MOUNTED_SPEED",
        ModDecreaseSpeed = 33 => "MOD_DECREASE_SPEED",
        ModIncreaseHealth = 34 => "MOD_INCREASE_HEALTH",
        ModIncreaseEnergy = 35 => "MOD_INCREASE_ENERGY",
        /// Stance/form, misc = `SpellShapeshiftForm.ID`.
        ModShapeshift = 36 => "MOD_SHAPESHIFT",
        EffectImmunity = 37 => "EFFECT_IMMUNITY",
        StateImmunity = 38 => "STATE_IMMUNITY",
        SchoolImmunity = 39 => "SCHOOL_IMMUNITY",
        DamageImmunity = 40 => "DAMAGE_IMMUNITY",
        DispelImmunity = 41 => "DISPEL_IMMUNITY",
        /// Proc: `EffectTriggerSpell` fires on `SpellAuraOptions.ProcTypeMask` events.
        ProcTriggerSpell = 42 => "PROC_TRIGGER_SPELL",
        ProcTriggerDamage = 43 => "PROC_TRIGGER_DAMAGE",
        TrackCreatures = 44 => "TRACK_CREATURES",
        TrackResources = 45 => "TRACK_RESOURCES",
        ModParryPercent = 47 => "MOD_PARRY_PERCENT",
        PeriodicTriggerSpellFromClient = 48 => "PERIODIC_TRIGGER_SPELL_FROM_CLIENT",
        ModDodgePercent = 49 => "MOD_DODGE_PERCENT",
        ModCriticalHealingAmount = 50 => "MOD_CRITICAL_HEALING_AMOUNT",
        ModBlockPercent = 51 => "MOD_BLOCK_PERCENT",
        /// Melee crit chance % (Cruelty).
        ModWeaponCritPercent = 52 => "MOD_WEAPON_CRIT_PERCENT",
        PeriodicLeech = 53 => "PERIODIC_LEECH",
        ModHitChance = 54 => "MOD_HIT_CHANCE",
        ModSpellHitChance = 55 => "MOD_SPELL_HIT_CHANCE",
        Transform = 56 => "TRANSFORM",
        ModSpellCritChance = 57 => "MOD_SPELL_CRIT_CHANCE",
        ModIncreaseSwimSpeed = 58 => "MOD_INCREASE_SWIM_SPEED",
        ModDamageDoneCreature = 59 => "MOD_DAMAGE_DONE_CREATURE",
        ModPacifySilence = 60 => "MOD_PACIFY_SILENCE",
        ModScale = 61 => "MOD_SCALE",
        PeriodicHealthFunnel = 62 => "PERIODIC_HEALTH_FUNNEL",
        PeriodicManaLeech = 64 => "PERIODIC_MANA_LEECH",
        ModCastingSpeedNotStack = 65 => "MOD_CASTING_SPEED_NOT_STACK",
        FeignDeath = 66 => "FEIGN_DEATH",
        ModDisarm = 67 => "MOD_DISARM",
        ModStalked = 68 => "MOD_STALKED",
        SchoolAbsorb = 69 => "SCHOOL_ABSORB",
        ModSpellCritChanceSchool = 71 => "MOD_SPELL_CRIT_CHANCE_SCHOOL",
        ModPowerCostSchoolPct = 72 => "MOD_POWER_COST_SCHOOL_PCT",
        ModPowerCostSchool = 73 => "MOD_POWER_COST_SCHOOL",
        ReflectSpellsSchool = 74 => "REFLECT_SPELLS_SCHOOL",
        ModLanguage = 75 => "MOD_LANGUAGE",
        FarSight = 76 => "FAR_SIGHT",
        MechanicImmunity = 77 => "MECHANIC_IMMUNITY",
        Mounted = 78 => "MOUNTED",
        /// Damage done %, misc = school mask (Death Wish, Two-Handed Weapon Specialization).
        ModDamagePercentDone = 79 => "MOD_DAMAGE_PERCENT_DONE",
        ModPercentStat = 80 => "MOD_PERCENT_STAT",
        SplitDamagePct = 81 => "SPLIT_DAMAGE_PCT",
        WaterBreathing = 82 => "WATER_BREATHING",
        ModBaseResistance = 83 => "MOD_BASE_RESISTANCE",
        ModRegen = 84 => "MOD_REGEN",
        /// Power regeneration, misc = power type (Anger Management).
        ModPowerRegen = 85 => "MOD_POWER_REGEN",
        ChannelDeathItem = 86 => "CHANNEL_DEATH_ITEM",
        /// Damage taken %, misc = school mask.
        ModDamagePercentTaken = 87 => "MOD_DAMAGE_PERCENT_TAKEN",
        ModHealthRegenPercent = 88 => "MOD_HEALTH_REGEN_PERCENT",
        PeriodicDamagePercent = 89 => "PERIODIC_DAMAGE_PERCENT",
        ModDetectRange = 91 => "MOD_DETECT_RANGE",
        PreventsFleeing = 92 => "PREVENTS_FLEEING",
        ModUnattackable = 93 => "MOD_UNATTACKABLE",
        InterruptRegen = 94 => "INTERRUPT_REGEN",
        Ghost = 95 => "GHOST",
        SpellMagnet = 96 => "SPELL_MAGNET",
        ManaShield = 97 => "MANA_SHIELD",
        ModSkillTalent = 98 => "MOD_SKILL_TALENT",
        /// Flat melee attack power (Battle Shout).
        ModAttackPower = 99 => "MOD_ATTACK_POWER",
        AurasVisible = 100 => "AURAS_VISIBLE",
        ModResistancePct = 101 => "MOD_RESISTANCE_PCT",
        ModMeleeAttackPowerVersus = 102 => "MOD_MELEE_ATTACK_POWER_VERSUS",
        ModTotalThreat = 103 => "MOD_TOTAL_THREAT",
        WaterWalk = 104 => "WATER_WALK",
        FeatherFall = 105 => "FEATHER_FALL",
        Hover = 106 => "HOVER",
        /// Flat spell modifier: misc = `SpellModOp`, `EffectSpellClassMask` = affected spells.
        AddFlatModifier = 107 => "ADD_FLAT_MODIFIER",
        /// Percent spell modifier: misc = `SpellModOp`, `EffectSpellClassMask` = affected spells.
        AddPctModifier = 108 => "ADD_PCT_MODIFIER",
        AddTargetTrigger = 109 => "ADD_TARGET_TRIGGER",
        ModPowerRegenPercent = 110 => "MOD_POWER_REGEN_PERCENT",
        InterceptMeleeRangedAttacks = 111 => "INTERCEPT_MELEE_RANGED_ATTACKS",
        OverrideClassScripts = 112 => "OVERRIDE_CLASS_SCRIPTS",
        ModRangedDamageTaken = 113 => "MOD_RANGED_DAMAGE_TAKEN",
        ModRangedDamageTakenPct = 114 => "MOD_RANGED_DAMAGE_TAKEN_PCT",
        ModHealing = 115 => "MOD_HEALING",
        ModRegenDuringCombat = 116 => "MOD_REGEN_DURING_COMBAT",
        ModMechanicResistance = 117 => "MOD_MECHANIC_RESISTANCE",
        /// Healing taken % (Mortal Strike −50).
        ModHealingPct = 118 => "MOD_HEALING_PCT",
        Untrackable = 120 => "UNTRACKABLE",
        Empathy = 121 => "EMPATHY",
        ModOffhandDamagePct = 122 => "MOD_OFFHAND_DAMAGE_PCT",
        ModTargetResistance = 123 => "MOD_TARGET_RESISTANCE",
        ModRangedAttackPower = 124 => "MOD_RANGED_ATTACK_POWER",
        ModMeleeDamageTaken = 125 => "MOD_MELEE_DAMAGE_TAKEN",
        ModMeleeDamageTakenPct = 126 => "MOD_MELEE_DAMAGE_TAKEN_PCT",
        RangedAttackPowerAttackerBonus = 127 => "RANGED_ATTACK_POWER_ATTACKER_BONUS",
        ModPossessPet = 128 => "MOD_POSSESS_PET",
        ModSpeedAlways = 129 => "MOD_SPEED_ALWAYS",
        ModMountedSpeedAlways = 130 => "MOD_MOUNTED_SPEED_ALWAYS",
        ModRangedAttackPowerVersus = 131 => "MOD_RANGED_ATTACK_POWER_VERSUS",
        ModIncreaseEnergyPercent = 132 => "MOD_INCREASE_ENERGY_PERCENT",
        ModIncreaseHealthPercent = 133 => "MOD_INCREASE_HEALTH_PERCENT",
        ModManaRegenInterrupt = 134 => "MOD_MANA_REGEN_INTERRUPT",
        ModHealingDone = 135 => "MOD_HEALING_DONE",
        ModHealingDonePercent = 136 => "MOD_HEALING_DONE_PERCENT",
        ModTotalStatPercentage = 137 => "MOD_TOTAL_STAT_PERCENTAGE",
        ModMeleeHaste = 138 => "MOD_MELEE_HASTE",
        ForceReaction = 139 => "FORCE_REACTION",
        ModRangedHaste = 140 => "MOD_RANGED_HASTE",
        ModBaseResistancePct = 142 => "MOD_BASE_RESISTANCE_PCT",
        ModResistanceExclusive = 143 => "MOD_RESISTANCE_EXCLUSIVE",
        SafeFall = 144 => "SAFE_FALL",
        ModPetTalentPoints = 145 => "MOD_PET_TALENT_POINTS",
        AllowTamePetType = 146 => "ALLOW_TAME_PET_TYPE",
        MechanicImmunityMask = 147 => "MECHANIC_IMMUNITY_MASK",
        ModChargeRecoveryRate = 148 => "MOD_CHARGE_RECOVERY_RATE",
        ReducePushback = 149 => "REDUCE_PUSHBACK",
        ModShieldBlockvaluePct = 150 => "MOD_SHIELD_BLOCKVALUE_PCT",
        TrackStealthed = 151 => "TRACK_STEALTHED",
        ModDetectedRange = 152 => "MOD_DETECTED_RANGE",
        ModStealthLevel = 154 => "MOD_STEALTH_LEVEL",
        ModWaterBreathing = 155 => "MOD_WATER_BREATHING",
        ModReputationGain = 156 => "MOD_REPUTATION_GAIN",
        PetDamageMulti = 157 => "PET_DAMAGE_MULTI",
        AllowTalentSwapping = 158 => "ALLOW_TALENT_SWAPPING",
        NoPvpCredit = 159 => "NO_PVP_CREDIT",
        ModHealthRegenInCombat = 161 => "MOD_HEALTH_REGEN_IN_COMBAT",
        PowerBurn = 162 => "POWER_BURN",
        ModCritDamageBonus = 163 => "MOD_CRIT_DAMAGE_BONUS",
        MeleeAttackPowerAttackerBonus = 165 => "MELEE_ATTACK_POWER_ATTACKER_BONUS",
        /// Attack power % (Blood Fury).
        ModAttackPowerPct = 166 => "MOD_ATTACK_POWER_PCT",
        ModRangedAttackPowerPct = 167 => "MOD_RANGED_ATTACK_POWER_PCT",
        ModDamageDoneVersus = 168 => "MOD_DAMAGE_DONE_VERSUS",
        SetFfaPvp = 169 => "SET_FFA_PVP",
        DetectAmore = 170 => "DETECT_AMORE",
        ModSpeedNotStack = 171 => "MOD_SPEED_NOT_STACK",
        ModMountedSpeedNotStack = 172 => "MOD_MOUNTED_SPEED_NOT_STACK",
        ModSpellDamageOfStatPercent = 174 => "MOD_SPELL_DAMAGE_OF_STAT_PERCENT",
        ModSpellHealingOfStatPercent = 175 => "MOD_SPELL_HEALING_OF_STAT_PERCENT",
        SpiritOfRedemption = 176 => "SPIRIT_OF_REDEMPTION",
        AoeCharm = 177 => "AOE_CHARM",
        ModMaxPowerPct = 178 => "MOD_MAX_POWER_PCT",
        ModPowerDisplay = 179 => "MOD_POWER_DISPLAY",
        ModFlatSpellDamageVersus = 180 => "MOD_FLAT_SPELL_DAMAGE_VERSUS",
        ModCriticalThreat = 183 => "MOD_CRITICAL_THREAT",
        ModAttackerMeleeHitChance = 184 => "MOD_ATTACKER_MELEE_HIT_CHANCE",
        ModAttackerRangedHitChance = 185 => "MOD_ATTACKER_RANGED_HIT_CHANCE",
        ModAttackerSpellHitChance = 186 => "MOD_ATTACKER_SPELL_HIT_CHANCE",
        ModAttackerMeleeCritChance = 187 => "MOD_ATTACKER_MELEE_CRIT_CHANCE",
        ModAttackerRangedCritChance = 188 => "MOD_ATTACKER_RANGED_CRIT_CHANCE",
        ModRating = 189 => "MOD_RATING",
        ModFactionReputationGain = 190 => "MOD_FACTION_REPUTATION_GAIN",
        UseNormalMovementSpeed = 191 => "USE_NORMAL_MOVEMENT_SPEED",
        ModMeleeRangedHaste = 192 => "MOD_MELEE_RANGED_HASTE",
        MeleeSlow = 193 => "MELEE_SLOW",
        ModTargetAbsorbSchool = 194 => "MOD_TARGET_ABSORB_SCHOOL",
        ModTargetAbilityAbsorbSchool = 195 => "MOD_TARGET_ABILITY_ABSORB_SCHOOL",
        ModCooldown = 196 => "MOD_COOLDOWN",
        ModAttackerSpellAndWeaponCritChance = 197 => "MOD_ATTACKER_SPELL_AND_WEAPON_CRIT_CHANCE",
        ModXpPct = 200 => "MOD_XP_PCT",
        Fly = 201 => "FLY",
        IgnoreCombatResult = 202 => "IGNORE_COMBAT_RESULT",
        ModAttackerMeleeCritDamage = 203 => "MOD_ATTACKER_MELEE_CRIT_DAMAGE",
        ModAttackerRangedCritDamage = 204 => "MOD_ATTACKER_RANGED_CRIT_DAMAGE",
        ModSchoolCritDmgTaken = 205 => "MOD_SCHOOL_CRIT_DMG_TAKEN",
        ModIncreaseVehicleFlightSpeed = 206 => "MOD_INCREASE_VEHICLE_FLIGHT_SPEED",
        ModIncreaseMountedFlightSpeed = 207 => "MOD_INCREASE_MOUNTED_FLIGHT_SPEED",
        ModIncreaseFlightSpeed = 208 => "MOD_INCREASE_FLIGHT_SPEED",
        ModMountedFlightSpeedAlways = 209 => "MOD_MOUNTED_FLIGHT_SPEED_ALWAYS",
        ModVehicleSpeedAlways = 210 => "MOD_VEHICLE_SPEED_ALWAYS",
        ModFlightSpeedNotStack = 211 => "MOD_FLIGHT_SPEED_NOT_STACK",
        ModRangedAttackPowerOfStatPercent = 212 => "MOD_RANGED_ATTACK_POWER_OF_STAT_PERCENT",
        ModRageFromDamageDealt = 213 => "MOD_RAGE_FROM_DAMAGE_DEALT",
        ArenaPreparation = 215 => "ARENA_PREPARATION",
        HasteSpells = 216 => "HASTE_SPELLS",
        ModMeleeHaste2 = 217 => "MOD_MELEE_HASTE_2",
        AddPctModifierBySpellLabel = 218 => "ADD_PCT_MODIFIER_BY_SPELL_LABEL",
        AddFlatModifierBySpellLabel = 219 => "ADD_FLAT_MODIFIER_BY_SPELL_LABEL",
        ModAbilitySchoolMask = 220 => "MOD_ABILITY_SCHOOL_MASK",
        ModDetaunt = 221 => "MOD_DETAUNT",
        RemoveTransmogCost = 222 => "REMOVE_TRANSMOG_COST",
        PreventRegeneratePower = 225 => "PREVENT_REGENERATE_POWER",
        /// Scripted periodic tick.
        PeriodicDummy = 226 => "PERIODIC_DUMMY",
        PeriodicTriggerSpellWithValue = 227 => "PERIODIC_TRIGGER_SPELL_WITH_VALUE",
        DetectStealth = 228 => "DETECT_STEALTH",
        ModAoeDamageAvoidance = 229 => "MOD_AOE_DAMAGE_AVOIDANCE",
        ModMaxHealth = 230 => "MOD_MAX_HEALTH",
        ProcTriggerSpellWithValue = 231 => "PROC_TRIGGER_SPELL_WITH_VALUE",
        /// Mechanic duration % (Iron Will); retail name unverified.
        ModMechanicDuration = 232 => "MOD_MECHANIC_DURATION",
        ChangeModelForAllHumanoids = 233 => "CHANGE_MODEL_FOR_ALL_HUMANOIDS",
        ModMechanicDurationNotStack = 234 => "MOD_MECHANIC_DURATION_NOT_STACK",
        ModDispelResist = 235 => "MOD_DISPEL_RESIST",
        ControlVehicle = 236 => "CONTROL_VEHICLE",
        ModSpellDamageOfAttackPower = 237 => "MOD_SPELL_DAMAGE_OF_ATTACK_POWER",
        ModSpellHealingOfAttackPower = 238 => "MOD_SPELL_HEALING_OF_ATTACK_POWER",
        ModScale2 = 239 => "MOD_SCALE_2",
        ModExpertise = 240 => "MOD_EXPERTISE",
        ForceMoveForward = 241 => "FORCE_MOVE_FORWARD",
        ModSpellDamageFromHealing = 242 => "MOD_SPELL_DAMAGE_FROM_HEALING",
        ModFaction = 243 => "MOD_FACTION",
        ComprehendLanguage = 244 => "COMPREHEND_LANGUAGE",
        ModAuraDurationByDispel = 245 => "MOD_AURA_DURATION_BY_DISPEL",
        ModAuraDurationByDispelNotStack = 246 => "MOD_AURA_DURATION_BY_DISPEL_NOT_STACK",
        CloneCaster = 247 => "CLONE_CASTER",
        ModCombatResultChance = 248 => "MOD_COMBAT_RESULT_CHANCE",
        ConvertRune = 249 => "CONVERT_RUNE",
        ModIncreaseHealth2 = 250 => "MOD_INCREASE_HEALTH_2",
        ModEnemyDodge = 251 => "MOD_ENEMY_DODGE",
        ModSpeedSlowAll = 252 => "MOD_SPEED_SLOW_ALL",
        ModBlockCritChance = 253 => "MOD_BLOCK_CRIT_CHANCE",
        ModDisarmOffhand = 254 => "MOD_DISARM_OFFHAND",
        ModMechanicDamageTakenPercent = 255 => "MOD_MECHANIC_DAMAGE_TAKEN_PERCENT",
        NoReagentUse = 256 => "NO_REAGENT_USE",
        ModTargetResistBySpellClass = 257 => "MOD_TARGET_RESIST_BY_SPELL_CLASS",
        OverrideSummonedObject = 258 => "OVERRIDE_SUMMONED_OBJECT",
        ModHotPct = 259 => "MOD_HOT_PCT",
        ScreenEffect = 260 => "SCREEN_EFFECT",
        Phase = 261 => "PHASE",
        AbilityIgnoreAurastate = 262 => "ABILITY_IGNORE_AURASTATE",
        DisableCastingExceptAbilities = 263 => "DISABLE_CASTING_EXCEPT_ABILITIES",
        DisableAttackingExceptAbilities = 264 => "DISABLE_ATTACKING_EXCEPT_ABILITIES",
        SetVignette = 266 => "SET_VIGNETTE",
        ModImmuneAuraApplySchool = 267 => "MOD_IMMUNE_AURA_APPLY_SCHOOL",
        ModArmorPctFromStat = 268 => "MOD_ARMOR_PCT_FROM_STAT",
        ModIgnoreTargetResist = 269 => "MOD_IGNORE_TARGET_RESIST",
        ModSchoolMaskDamageFromCaster = 270 => "MOD_SCHOOL_MASK_DAMAGE_FROM_CASTER",
        ModSpellDamageFromCaster = 271 => "MOD_SPELL_DAMAGE_FROM_CASTER",
        ModBlockValuePct = 272 => "MOD_BLOCK_VALUE_PCT",
        XRay = 273 => "X_RAY",
        ModBlockValueFlat = 274 => "MOD_BLOCK_VALUE_FLAT",
        ModIgnoreShapeshift = 275 => "MOD_IGNORE_SHAPESHIFT",
        ModDamageDoneForMechanic = 276 => "MOD_DAMAGE_DONE_FOR_MECHANIC",
        ModMaxAffectedTargets = 277 => "MOD_MAX_AFFECTED_TARGETS",
        ModDisarmRanged = 278 => "MOD_DISARM_RANGED",
        InitializeImages = 279 => "INITIALIZE_IMAGES",
        /// Armor penetration % (Weaponmaster maces).
        ModArmorPenetrationPct = 280 => "MOD_ARMOR_PENETRATION_PCT",
        ModHonorGainPct = 281 => "MOD_HONOR_GAIN_PCT",
        ModBaseHealthPct = 282 => "MOD_BASE_HEALTH_PCT",
        ModHealingReceived = 283 => "MOD_HEALING_RECEIVED",
        Linked = 284 => "LINKED",
        Linked2 = 285 => "LINKED_2",
        ModRecoveryRate = 286 => "MOD_RECOVERY_RATE",
        DeflectSpells = 287 => "DEFLECT_SPELLS",
        IgnoreHitDirection = 288 => "IGNORE_HIT_DIRECTION",
        PreventDurabilityLoss = 289 => "PREVENT_DURABILITY_LOSS",
        /// Crit chance % for spells and attacks (Berserker Stance, Recklessness).
        ModCritPct = 290 => "MOD_CRIT_PCT",
        ModXpQuestPct = 291 => "MOD_XP_QUEST_PCT",
        OpenStable = 292 => "OPEN_STABLE",
        OverrideSpells = 293 => "OVERRIDE_SPELLS",
        PreventRegeneratePower2 = 294 => "PREVENT_REGENERATE_POWER_2",
        ModPeriodicDamageTaken = 295 => "MOD_PERIODIC_DAMAGE_TAKEN",
        SetPowerType = 296 => "SET_POWER_TYPE",
        TriggerSpellOnPowerPct = 297 => "TRIGGER_SPELL_ON_POWER_PCT",
        ShareDamagePct = 300 => "SHARE_DAMAGE_PCT",
        SchoolHealAbsorb = 301 => "SCHOOL_HEAL_ABSORB",
        ModDamageDoneVersusAurastate = 303 => "MOD_DAMAGE_DONE_VERSUS_AURASTATE",
        ModFakeInebriate = 304 => "MOD_FAKE_INEBRIATE",
        ModMinimumSpeed = 305 => "MOD_MINIMUM_SPEED",
        ModCritChanceForCaster = 306 => "MOD_CRIT_CHANCE_FOR_CASTER",
        CastWhileWalkingBySpellLabel = 307 => "CAST_WHILE_WALKING_BY_SPELL_LABEL",
        ModCritChanceForCasterWithAbilities = 308 => "MOD_CRIT_CHANCE_FOR_CASTER_WITH_ABILITIES",
        ModResilience = 309 => "MOD_RESILIENCE",
        ModCreatureAoeDamageAvoidance = 310 => "MOD_CREATURE_AOE_DAMAGE_AVOIDANCE",
        IgnoreCombat = 311 => "IGNORE_COMBAT",
        AnimReplacementSet = 312 => "ANIM_REPLACEMENT_SET",
        PreventResurrection = 314 => "PREVENT_RESURRECTION",
        UnderwaterWalking = 315 => "UNDERWATER_WALKING",
        SchoolAbsorbOverkill = 316 => "SCHOOL_ABSORB_OVERKILL",
        ModSpellPowerPct = 317 => "MOD_SPELL_POWER_PCT",
        Mastery = 318 => "MASTERY",
        /// Melee attack speed % (Flurry, Berserking).
        ModMeleeHaste3 = 319 => "MOD_MELEE_HASTE_3",
        ModRangedHaste2 = 320 => "MOD_RANGED_HASTE_2",
        ModNoActions = 321 => "MOD_NO_ACTIONS",
        InterfereTargetting = 322 => "INTERFERE_TARGETTING",
        PhaseGroup = 326 => "PHASE_GROUP",
        PhaseAlwaysVisible = 327 => "PHASE_ALWAYS_VISIBLE",
        TriggerSpellOnPowerAmount = 328 => "TRIGGER_SPELL_ON_POWER_AMOUNT",
        ModPowerGainPct = 329 => "MOD_POWER_GAIN_PCT",
        CastWhileWalking = 330 => "CAST_WHILE_WALKING",
        ForceWeather = 331 => "FORCE_WEATHER",
        /// Replaces the action-bar spell misc with the spell in base points (runes, Improved Slam).
        OverrideActionbarSpells = 332 => "OVERRIDE_ACTIONBAR_SPELLS",
        OverrideActionbarSpellsTriggered = 333 => "OVERRIDE_ACTIONBAR_SPELLS_TRIGGERED",
        ModAutoattackRange = 334 => "MOD_AUTOATTACK_RANGE",
        MountRestrictions = 336 => "MOUNT_RESTRICTIONS",
        ModVendorItemsPrices = 337 => "MOD_VENDOR_ITEMS_PRICES",
        ModDurabilityLoss = 338 => "MOD_DURABILITY_LOSS",
        ModCritChanceForCasterPet = 339 => "MOD_CRIT_CHANCE_FOR_CASTER_PET",
        ModResurrectedHealthByGuildMember = 340 => "MOD_RESURRECTED_HEALTH_BY_GUILD_MEMBER",
        ModSpellCategoryCooldown = 341 => "MOD_SPELL_CATEGORY_COOLDOWN",
        ModMeleeRangedHaste2 = 342 => "MOD_MELEE_RANGED_HASTE_2",
        ModMeleeDamageFromCaster = 343 => "MOD_MELEE_DAMAGE_FROM_CASTER",
        ModAutoattackDamage = 344 => "MOD_AUTOATTACK_DAMAGE",
        BypassArmorForCaster = 345 => "BYPASS_ARMOR_FOR_CASTER",
        EnableAltPower = 346 => "ENABLE_ALT_POWER",
        ModSpellCooldownByHaste = 347 => "MOD_SPELL_COOLDOWN_BY_HASTE",
        ModMoneyGain = 348 => "MOD_MONEY_GAIN",
        ModCurrencyGain = 349 => "MOD_CURRENCY_GAIN",
        /// Max power, misc = power type (Boundless Rage); retail name unverified.
        ModMaxPower = 418 => "MOD_MAX_POWER",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ids_and_names_round_trip() {
        for aura in AuraType::KNOWN {
            assert_eq!(AuraType::from_id(aura.id()), *aura);
            assert_eq!(AuraType::from_name(aura.name().unwrap()), Some(*aura));
            assert_eq!(aura.to_string().parse::<AuraType>().unwrap(), *aura);
        }
        let ids: Vec<u32> = AuraType::KNOWN.iter().map(|a| a.id()).collect();
        assert!(
            ids.windows(2).all(|w| w[0] < w[1]),
            "ids are unique and ascending"
        );
    }

    #[test]
    fn values_seen_on_player_spells_have_the_documented_names() {
        let seen = [
            (3, "PERIODIC_DAMAGE"),
            (4, "DUMMY"),
            (10, "MOD_THREAT"),
            (13, "MOD_DAMAGE_DONE"),
            (22, "MOD_RESISTANCE"),
            (23, "PERIODIC_TRIGGER_SPELL"),
            (24, "PERIODIC_ENERGIZE"),
            (29, "MOD_STAT"),
            (30, "MOD_SKILL"),
            (36, "MOD_SHAPESHIFT"),
            (42, "PROC_TRIGGER_SPELL"),
            (52, "MOD_WEAPON_CRIT_PERCENT"),
            (54, "MOD_HIT_CHANCE"),
            (55, "MOD_SPELL_HIT_CHANCE"),
            (65, "MOD_CASTING_SPEED_NOT_STACK"),
            (77, "MECHANIC_IMMUNITY"),
            (79, "MOD_DAMAGE_PERCENT_DONE"),
            (85, "MOD_POWER_REGEN"),
            (87, "MOD_DAMAGE_PERCENT_TAKEN"),
            (99, "MOD_ATTACK_POWER"),
            (107, "ADD_FLAT_MODIFIER"),
            (108, "ADD_PCT_MODIFIER"),
            (112, "OVERRIDE_CLASS_SCRIPTS"),
            (118, "MOD_HEALING_PCT"),
            (122, "MOD_OFFHAND_DAMAGE_PCT"),
            (124, "MOD_RANGED_ATTACK_POWER"),
            (137, "MOD_TOTAL_STAT_PERCENTAGE"),
            (142, "MOD_BASE_RESISTANCE_PCT"),
            (166, "MOD_ATTACK_POWER_PCT"),
            (226, "PERIODIC_DUMMY"),
            (232, "MOD_MECHANIC_DURATION"),
            (280, "MOD_ARMOR_PENETRATION_PCT"),
            (290, "MOD_CRIT_PCT"),
            (319, "MOD_MELEE_HASTE_3"),
            (332, "OVERRIDE_ACTIONBAR_SPELLS"),
            (418, "MOD_MAX_POWER"),
        ];
        for (id, name) in seen {
            assert_eq!(AuraType::from_id(id).name(), Some(name), "{id}");
        }
        // Toughness' second effect: no retail name known, loads as unknown.
        assert_eq!(AuraType::from_id(466), AuraType::Unknown(466));
        assert_eq!(AuraType::Unknown(466).to_string(), "UNKNOWN_466");
    }

    #[test]
    fn serde_accepts_both_forms() {
        assert_eq!(
            serde_yaml::from_str::<AuraType>("PROC_TRIGGER_SPELL").unwrap(),
            AuraType::ProcTriggerSpell
        );
        assert_eq!(
            serde_yaml::from_str::<AuraType>("42").unwrap(),
            AuraType::ProcTriggerSpell
        );
        assert_eq!(
            serde_yaml::from_str::<AuraType>("466").unwrap(),
            AuraType::Unknown(466)
        );
        assert_eq!(
            serde_yaml::to_string(&AuraType::Unknown(466))
                .unwrap()
                .trim(),
            "466"
        );
    }
}
